/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkoutLinksCreate } from "../../funcs/checkoutLinksCreate.js";
import { CheckoutLinksCreateCheckoutLinkCreate$inboundSchema } from "../../models/operations/checkoutlinkscreate.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CheckoutLinksCreateCheckoutLinkCreate$inboundSchema,
};

export const tool$checkoutLinksCreate: ToolDefinition<typeof args> = {
  name: "checkout-links_create",
  description: `Create Checkout Link

Create a checkout link.

**Scopes**: \`checkout_links:write\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await checkoutLinksCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
