/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetBalance } from "../../funcs/customersGetBalance.js";
import { CustomersGetBalanceRequest$inboundSchema } from "../../models/operations/customersgetbalance.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CustomersGetBalanceRequest$inboundSchema,
};

export const tool$customersGetBalance: ToolDefinition<typeof args> = {
  name: "customers-get-balance",
  description: `Get Customer Balance

Get customer balance information.

**Scopes**: \`customers:read\` \`customers:write\``,
  scopes: ["read", "customers"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersGetBalance(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
