/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customFieldsDelete } from "../../funcs/customFieldsDelete.js";
import { CustomFieldsDeleteRequest$inboundSchema } from "../../models/operations/customfieldsdelete.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CustomFieldsDeleteRequest$inboundSchema,
};

export const tool$customFieldsDelete: ToolDefinition<typeof args> = {
  name: "custom-fields_delete",
  description: `Delete Custom Field

Delete a custom field.

**Scopes**: \`custom_fields:write\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customFieldsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
