/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersExport } from "../../funcs/customersExport.js";
import { CustomersExportRequest$inboundSchema } from "../../models/operations/customersexport.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CustomersExportRequest$inboundSchema,
};

export const tool$customersExport: ToolDefinition<typeof args> = {
  name: "customers-export",
  description: `Export Customers

Export customers as a CSV file.

**Scopes**: \`customers:read\` \`customers:write\``,
  scopes: ["read", "customers"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersExport(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
