/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkoutsCreate } from "../funcs/checkoutsCreate.js";
import { checkoutsRetrieve } from "../funcs/checkoutsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Checkouts extends ClientSDK {
    /**
     * Create Checkout
     *
     * @remarks
     * Create a checkout session.
     */
    async create(
        request: components.CheckoutCreate,
        options?: RequestOptions
    ): Promise<components.Checkout> {
        return unwrapAsync(checkoutsCreate(this, request, options));
    }

    /**
     * Get Checkout
     *
     * @remarks
     * Get an active checkout session by ID.
     */
    async retrieve(
        request: operations.CheckoutsGetRequest,
        options?: RequestOptions
    ): Promise<components.Checkout> {
        return unwrapAsync(checkoutsRetrieve(this, request, options));
    }
}
