/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerSessionsCreate } from "../funcs/customerSessionsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { CustomerSession } from "../models/components/customersession.js";
import { CustomerSessionCreate } from "../models/components/customersessioncreate.js";
import { unwrapAsync } from "../types/fp.js";

export class CustomerSessions extends ClientSDK {
  /**
   * Create Customer Session
   *
   * @remarks
   * Create a customer session.
   */
  async create(
    request: CustomerSessionCreate,
    options?: RequestOptions,
  ): Promise<CustomerSession> {
    return unwrapAsync(customerSessionsCreate(
      this,
      request,
      options,
    ));
  }
}
