/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerPortalOrganizationsGet } from "../funcs/customerPortalOrganizationsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { Organization } from "../models/components/organization.js";
import { CustomerPortalOrganizationsGetRequest } from "../models/operations/customerportalorganizationsget.js";
import { unwrapAsync } from "../types/fp.js";

export class PolarOrganizations extends ClientSDK {
  /**
   * Get Organization
   *
   * @remarks
   * Get a customer portal's organization by slug.
   */
  async get(
    request: CustomerPortalOrganizationsGetRequest,
    options?: RequestOptions,
  ): Promise<Organization> {
    return unwrapAsync(customerPortalOrganizationsGet(
      this,
      request,
      options,
    ));
  }
}
