workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Polar-OAS:
        inputs:
            - location: https://api.polar.sh/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/type_parameter.yml
        registry:
            location: registry.speakeasyapi.dev/polar/polar/polar-oas
targets:
    polar:
        target: typescript
        source: Polar-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
          output: codeSamples.yaml
