workflowVersion: 1.0.0
speakeasyVersion: 1.561.0
sources:
  Polar-OAS:
    inputs:
      - location: https://api.polar.sh/openapi.json
    overlays:
      - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/security.yml
      - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/type_parameter.yml
      - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/read_only.yml
      - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/event_discriminator.yml
    registry:
      location: registry.speakeasyapi.dev/polar/polar/polar-oas
targets:
  polar:
    target: typescript
    source: Polar-OAS
    publish:
      npm:
        token: $npm_token
    codeSamples:
      output: codeSamples.yaml
      registry:
        location: registry.speakeasyapi.dev/polar/polar/polar-oas-ts-code-samples
      labelOverride:
        fixedValue: Typescript (SDK)
