/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CustomersDeleteExternalRequest = {
  /**
   * The customer external ID.
   */
  externalId: string;
  /**
   * If true, also anonymize the customer's personal data for GDPR compliance.
   */
  anonymize?: boolean | undefined;
};

/** @internal */
export type CustomersDeleteExternalRequest$Outbound = {
  external_id: string;
  anonymize: boolean;
};

/** @internal */
export const CustomersDeleteExternalRequest$outboundSchema: z.ZodMiniType<
  CustomersDeleteExternalRequest$Outbound,
  CustomersDeleteExternalRequest
> = z.pipe(
  z.object({
    externalId: z.string(),
    anonymize: z._default(z.boolean(), false),
  }),
  z.transform((v) => {
    return remap$(v, {
      externalId: "external_id",
    });
  }),
);

export function customersDeleteExternalRequestToJSON(
  customersDeleteExternalRequest: CustomersDeleteExternalRequest,
): string {
  return JSON.stringify(
    CustomersDeleteExternalRequest$outboundSchema.parse(
      customersDeleteExternalRequest,
    ),
  );
}
