/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CustomFieldUpdate,
  CustomFieldUpdate$Outbound,
  CustomFieldUpdate$outboundSchema,
} from "../components/customfieldupdate.js";

export type CustomFieldsUpdateRequest = {
  /**
   * The custom field ID.
   */
  id: string;
  customFieldUpdate: CustomFieldUpdate;
};

/** @internal */
export type CustomFieldsUpdateRequest$Outbound = {
  id: string;
  CustomFieldUpdate: CustomFieldUpdate$Outbound;
};

/** @internal */
export const CustomFieldsUpdateRequest$outboundSchema: z.ZodType<
  CustomFieldsUpdateRequest$Outbound,
  z.ZodTypeDef,
  CustomFieldsUpdateRequest
> = z.object({
  id: z.string(),
  customFieldUpdate: CustomFieldUpdate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    customFieldUpdate: "CustomFieldUpdate",
  });
});

export function customFieldsUpdateRequestToJSON(
  customFieldsUpdateRequest: CustomFieldsUpdateRequest,
): string {
  return JSON.stringify(
    CustomFieldsUpdateRequest$outboundSchema.parse(customFieldsUpdateRequest),
  );
}
