/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DisputesAcceptRequest = {
  /**
   * The dispute ID.
   */
  id: string;
};

/** @internal */
export type DisputesAcceptRequest$Outbound = {
  id: string;
};

/** @internal */
export const DisputesAcceptRequest$outboundSchema: z.ZodMiniType<
  DisputesAcceptRequest$Outbound,
  DisputesAcceptRequest
> = z.object({
  id: z.string(),
});

export function disputesAcceptRequestToJSON(
  disputesAcceptRequest: DisputesAcceptRequest,
): string {
  return JSON.stringify(
    DisputesAcceptRequest$outboundSchema.parse(disputesAcceptRequest),
  );
}
