/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Successful Response
 */
export type Oauth2UserinfoResponseOauth2Userinfo =
  | components.UserInfoOrganization
  | components.UserInfoUser;

/** @internal */
export const Oauth2UserinfoResponseOauth2Userinfo$inboundSchema: z.ZodType<
  Oauth2UserinfoResponseOauth2Userinfo,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.UserInfoOrganization$inboundSchema,
  components.UserInfoUser$inboundSchema,
]);

/** @internal */
export type Oauth2UserinfoResponseOauth2Userinfo$Outbound =
  | components.UserInfoOrganization$Outbound
  | components.UserInfoUser$Outbound;

/** @internal */
export const Oauth2UserinfoResponseOauth2Userinfo$outboundSchema: z.ZodType<
  Oauth2UserinfoResponseOauth2Userinfo$Outbound,
  z.ZodTypeDef,
  Oauth2UserinfoResponseOauth2Userinfo
> = z.union([
  components.UserInfoOrganization$outboundSchema,
  components.UserInfoUser$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Oauth2UserinfoResponseOauth2Userinfo$ {
  /** @deprecated use `Oauth2UserinfoResponseOauth2Userinfo$inboundSchema` instead. */
  export const inboundSchema =
    Oauth2UserinfoResponseOauth2Userinfo$inboundSchema;
  /** @deprecated use `Oauth2UserinfoResponseOauth2Userinfo$outboundSchema` instead. */
  export const outboundSchema =
    Oauth2UserinfoResponseOauth2Userinfo$outboundSchema;
  /** @deprecated use `Oauth2UserinfoResponseOauth2Userinfo$Outbound` instead. */
  export type Outbound = Oauth2UserinfoResponseOauth2Userinfo$Outbound;
}

export function oauth2UserinfoResponseOauth2UserinfoToJSON(
  oauth2UserinfoResponseOauth2Userinfo: Oauth2UserinfoResponseOauth2Userinfo,
): string {
  return JSON.stringify(
    Oauth2UserinfoResponseOauth2Userinfo$outboundSchema.parse(
      oauth2UserinfoResponseOauth2Userinfo,
    ),
  );
}

export function oauth2UserinfoResponseOauth2UserinfoFromJSON(
  jsonString: string,
): SafeParseResult<Oauth2UserinfoResponseOauth2Userinfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Oauth2UserinfoResponseOauth2Userinfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Oauth2UserinfoResponseOauth2Userinfo' from JSON`,
  );
}
