/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ListResourceOrder,
  ListResourceOrder$inboundSchema,
  ListResourceOrder$Outbound,
  ListResourceOrder$outboundSchema,
} from "../components/listresourceorder.js";
import {
  OrderSortProperty,
  OrderSortProperty$inboundSchema,
  OrderSortProperty$outboundSchema,
} from "../components/ordersortproperty.js";
import {
  ProductBillingType,
  ProductBillingType$inboundSchema,
  ProductBillingType$outboundSchema,
} from "../components/productbillingtype.js";
import {
  MetadataQuery,
  MetadataQuery$inboundSchema,
  MetadataQuery$Outbound,
  MetadataQuery$outboundSchema,
} from "../components/subscriptionslist.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter by organization ID.
 */
export type OrdersListQueryParamOrganizationIDFilter = string | Array<string>;

/**
 * Filter by product ID.
 */
export type OrdersListQueryParamProductIDFilter = string | Array<string>;

/**
 * Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
 */
export type ProductBillingTypeFilter =
  | ProductBillingType
  | Array<ProductBillingType>;

/**
 * Filter by discount ID.
 */
export type QueryParamDiscountIDFilter = string | Array<string>;

/**
 * Filter by customer ID.
 */
export type OrdersListQueryParamCustomerIDFilter = string | Array<string>;

/**
 * Filter by checkout ID.
 */
export type CheckoutIDFilter = string | Array<string>;

export type OrdersListRequest = {
  /**
   * Filter by organization ID.
   */
  organizationId?: string | Array<string> | null | undefined;
  /**
   * Filter by product ID.
   */
  productId?: string | Array<string> | null | undefined;
  /**
   * Filter by product billing type. `recurring` will filter data corresponding to subscriptions creations or renewals. `one_time` will filter data corresponding to one-time purchases.
   */
  productBillingType?:
    | ProductBillingType
    | Array<ProductBillingType>
    | null
    | undefined;
  /**
   * Filter by discount ID.
   */
  discountId?: string | Array<string> | null | undefined;
  /**
   * Filter by customer ID.
   */
  customerId?: string | Array<string> | null | undefined;
  /**
   * Filter by checkout ID.
   */
  checkoutId?: string | Array<string> | null | undefined;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
   */
  sorting?: Array<OrderSortProperty> | null | undefined;
  /**
   * Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
   */
  metadata?: { [k: string]: MetadataQuery } | null | undefined;
};

export type OrdersListResponse = {
  result: ListResourceOrder;
};

/** @internal */
export const OrdersListQueryParamOrganizationIDFilter$inboundSchema: z.ZodType<
  OrdersListQueryParamOrganizationIDFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type OrdersListQueryParamOrganizationIDFilter$Outbound =
  | string
  | Array<string>;

/** @internal */
export const OrdersListQueryParamOrganizationIDFilter$outboundSchema: z.ZodType<
  OrdersListQueryParamOrganizationIDFilter$Outbound,
  z.ZodTypeDef,
  OrdersListQueryParamOrganizationIDFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrdersListQueryParamOrganizationIDFilter$ {
  /** @deprecated use `OrdersListQueryParamOrganizationIDFilter$inboundSchema` instead. */
  export const inboundSchema =
    OrdersListQueryParamOrganizationIDFilter$inboundSchema;
  /** @deprecated use `OrdersListQueryParamOrganizationIDFilter$outboundSchema` instead. */
  export const outboundSchema =
    OrdersListQueryParamOrganizationIDFilter$outboundSchema;
  /** @deprecated use `OrdersListQueryParamOrganizationIDFilter$Outbound` instead. */
  export type Outbound = OrdersListQueryParamOrganizationIDFilter$Outbound;
}

export function ordersListQueryParamOrganizationIDFilterToJSON(
  ordersListQueryParamOrganizationIDFilter:
    OrdersListQueryParamOrganizationIDFilter,
): string {
  return JSON.stringify(
    OrdersListQueryParamOrganizationIDFilter$outboundSchema.parse(
      ordersListQueryParamOrganizationIDFilter,
    ),
  );
}

export function ordersListQueryParamOrganizationIDFilterFromJSON(
  jsonString: string,
): SafeParseResult<
  OrdersListQueryParamOrganizationIDFilter,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OrdersListQueryParamOrganizationIDFilter$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OrdersListQueryParamOrganizationIDFilter' from JSON`,
  );
}

/** @internal */
export const OrdersListQueryParamProductIDFilter$inboundSchema: z.ZodType<
  OrdersListQueryParamProductIDFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type OrdersListQueryParamProductIDFilter$Outbound =
  | string
  | Array<string>;

/** @internal */
export const OrdersListQueryParamProductIDFilter$outboundSchema: z.ZodType<
  OrdersListQueryParamProductIDFilter$Outbound,
  z.ZodTypeDef,
  OrdersListQueryParamProductIDFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrdersListQueryParamProductIDFilter$ {
  /** @deprecated use `OrdersListQueryParamProductIDFilter$inboundSchema` instead. */
  export const inboundSchema =
    OrdersListQueryParamProductIDFilter$inboundSchema;
  /** @deprecated use `OrdersListQueryParamProductIDFilter$outboundSchema` instead. */
  export const outboundSchema =
    OrdersListQueryParamProductIDFilter$outboundSchema;
  /** @deprecated use `OrdersListQueryParamProductIDFilter$Outbound` instead. */
  export type Outbound = OrdersListQueryParamProductIDFilter$Outbound;
}

export function ordersListQueryParamProductIDFilterToJSON(
  ordersListQueryParamProductIDFilter: OrdersListQueryParamProductIDFilter,
): string {
  return JSON.stringify(
    OrdersListQueryParamProductIDFilter$outboundSchema.parse(
      ordersListQueryParamProductIDFilter,
    ),
  );
}

export function ordersListQueryParamProductIDFilterFromJSON(
  jsonString: string,
): SafeParseResult<OrdersListQueryParamProductIDFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OrdersListQueryParamProductIDFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersListQueryParamProductIDFilter' from JSON`,
  );
}

/** @internal */
export const ProductBillingTypeFilter$inboundSchema: z.ZodType<
  ProductBillingTypeFilter,
  z.ZodTypeDef,
  unknown
> = z.union([
  ProductBillingType$inboundSchema,
  z.array(ProductBillingType$inboundSchema),
]);

/** @internal */
export type ProductBillingTypeFilter$Outbound = string | Array<string>;

/** @internal */
export const ProductBillingTypeFilter$outboundSchema: z.ZodType<
  ProductBillingTypeFilter$Outbound,
  z.ZodTypeDef,
  ProductBillingTypeFilter
> = z.union([
  ProductBillingType$outboundSchema,
  z.array(ProductBillingType$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductBillingTypeFilter$ {
  /** @deprecated use `ProductBillingTypeFilter$inboundSchema` instead. */
  export const inboundSchema = ProductBillingTypeFilter$inboundSchema;
  /** @deprecated use `ProductBillingTypeFilter$outboundSchema` instead. */
  export const outboundSchema = ProductBillingTypeFilter$outboundSchema;
  /** @deprecated use `ProductBillingTypeFilter$Outbound` instead. */
  export type Outbound = ProductBillingTypeFilter$Outbound;
}

export function productBillingTypeFilterToJSON(
  productBillingTypeFilter: ProductBillingTypeFilter,
): string {
  return JSON.stringify(
    ProductBillingTypeFilter$outboundSchema.parse(productBillingTypeFilter),
  );
}

export function productBillingTypeFilterFromJSON(
  jsonString: string,
): SafeParseResult<ProductBillingTypeFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductBillingTypeFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductBillingTypeFilter' from JSON`,
  );
}

/** @internal */
export const QueryParamDiscountIDFilter$inboundSchema: z.ZodType<
  QueryParamDiscountIDFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type QueryParamDiscountIDFilter$Outbound = string | Array<string>;

/** @internal */
export const QueryParamDiscountIDFilter$outboundSchema: z.ZodType<
  QueryParamDiscountIDFilter$Outbound,
  z.ZodTypeDef,
  QueryParamDiscountIDFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryParamDiscountIDFilter$ {
  /** @deprecated use `QueryParamDiscountIDFilter$inboundSchema` instead. */
  export const inboundSchema = QueryParamDiscountIDFilter$inboundSchema;
  /** @deprecated use `QueryParamDiscountIDFilter$outboundSchema` instead. */
  export const outboundSchema = QueryParamDiscountIDFilter$outboundSchema;
  /** @deprecated use `QueryParamDiscountIDFilter$Outbound` instead. */
  export type Outbound = QueryParamDiscountIDFilter$Outbound;
}

export function queryParamDiscountIDFilterToJSON(
  queryParamDiscountIDFilter: QueryParamDiscountIDFilter,
): string {
  return JSON.stringify(
    QueryParamDiscountIDFilter$outboundSchema.parse(queryParamDiscountIDFilter),
  );
}

export function queryParamDiscountIDFilterFromJSON(
  jsonString: string,
): SafeParseResult<QueryParamDiscountIDFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryParamDiscountIDFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryParamDiscountIDFilter' from JSON`,
  );
}

/** @internal */
export const OrdersListQueryParamCustomerIDFilter$inboundSchema: z.ZodType<
  OrdersListQueryParamCustomerIDFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type OrdersListQueryParamCustomerIDFilter$Outbound =
  | string
  | Array<string>;

/** @internal */
export const OrdersListQueryParamCustomerIDFilter$outboundSchema: z.ZodType<
  OrdersListQueryParamCustomerIDFilter$Outbound,
  z.ZodTypeDef,
  OrdersListQueryParamCustomerIDFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrdersListQueryParamCustomerIDFilter$ {
  /** @deprecated use `OrdersListQueryParamCustomerIDFilter$inboundSchema` instead. */
  export const inboundSchema =
    OrdersListQueryParamCustomerIDFilter$inboundSchema;
  /** @deprecated use `OrdersListQueryParamCustomerIDFilter$outboundSchema` instead. */
  export const outboundSchema =
    OrdersListQueryParamCustomerIDFilter$outboundSchema;
  /** @deprecated use `OrdersListQueryParamCustomerIDFilter$Outbound` instead. */
  export type Outbound = OrdersListQueryParamCustomerIDFilter$Outbound;
}

export function ordersListQueryParamCustomerIDFilterToJSON(
  ordersListQueryParamCustomerIDFilter: OrdersListQueryParamCustomerIDFilter,
): string {
  return JSON.stringify(
    OrdersListQueryParamCustomerIDFilter$outboundSchema.parse(
      ordersListQueryParamCustomerIDFilter,
    ),
  );
}

export function ordersListQueryParamCustomerIDFilterFromJSON(
  jsonString: string,
): SafeParseResult<OrdersListQueryParamCustomerIDFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OrdersListQueryParamCustomerIDFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersListQueryParamCustomerIDFilter' from JSON`,
  );
}

/** @internal */
export const CheckoutIDFilter$inboundSchema: z.ZodType<
  CheckoutIDFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type CheckoutIDFilter$Outbound = string | Array<string>;

/** @internal */
export const CheckoutIDFilter$outboundSchema: z.ZodType<
  CheckoutIDFilter$Outbound,
  z.ZodTypeDef,
  CheckoutIDFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutIDFilter$ {
  /** @deprecated use `CheckoutIDFilter$inboundSchema` instead. */
  export const inboundSchema = CheckoutIDFilter$inboundSchema;
  /** @deprecated use `CheckoutIDFilter$outboundSchema` instead. */
  export const outboundSchema = CheckoutIDFilter$outboundSchema;
  /** @deprecated use `CheckoutIDFilter$Outbound` instead. */
  export type Outbound = CheckoutIDFilter$Outbound;
}

export function checkoutIDFilterToJSON(
  checkoutIDFilter: CheckoutIDFilter,
): string {
  return JSON.stringify(
    CheckoutIDFilter$outboundSchema.parse(checkoutIDFilter),
  );
}

export function checkoutIDFilterFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutIDFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckoutIDFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutIDFilter' from JSON`,
  );
}

/** @internal */
export const OrdersListRequest$inboundSchema: z.ZodType<
  OrdersListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  product_id: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  product_billing_type: z.nullable(
    z.union([
      ProductBillingType$inboundSchema,
      z.array(ProductBillingType$inboundSchema),
    ]),
  ).optional(),
  discount_id: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  customer_id: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  checkout_id: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  sorting: z.nullable(z.array(OrderSortProperty$inboundSchema)).optional(),
  metadata: z.nullable(z.record(MetadataQuery$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
    "product_id": "productId",
    "product_billing_type": "productBillingType",
    "discount_id": "discountId",
    "customer_id": "customerId",
    "checkout_id": "checkoutId",
  });
});

/** @internal */
export type OrdersListRequest$Outbound = {
  organization_id?: string | Array<string> | null | undefined;
  product_id?: string | Array<string> | null | undefined;
  product_billing_type?: string | Array<string> | null | undefined;
  discount_id?: string | Array<string> | null | undefined;
  customer_id?: string | Array<string> | null | undefined;
  checkout_id?: string | Array<string> | null | undefined;
  page: number;
  limit: number;
  sorting?: Array<string> | null | undefined;
  metadata?: { [k: string]: MetadataQuery$Outbound } | null | undefined;
};

/** @internal */
export const OrdersListRequest$outboundSchema: z.ZodType<
  OrdersListRequest$Outbound,
  z.ZodTypeDef,
  OrdersListRequest
> = z.object({
  organizationId: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  productId: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  productBillingType: z.nullable(
    z.union([
      ProductBillingType$outboundSchema,
      z.array(ProductBillingType$outboundSchema),
    ]),
  ).optional(),
  discountId: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  customerId: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  checkoutId: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  sorting: z.nullable(z.array(OrderSortProperty$outboundSchema)).optional(),
  metadata: z.nullable(z.record(MetadataQuery$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    productId: "product_id",
    productBillingType: "product_billing_type",
    discountId: "discount_id",
    customerId: "customer_id",
    checkoutId: "checkout_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrdersListRequest$ {
  /** @deprecated use `OrdersListRequest$inboundSchema` instead. */
  export const inboundSchema = OrdersListRequest$inboundSchema;
  /** @deprecated use `OrdersListRequest$outboundSchema` instead. */
  export const outboundSchema = OrdersListRequest$outboundSchema;
  /** @deprecated use `OrdersListRequest$Outbound` instead. */
  export type Outbound = OrdersListRequest$Outbound;
}

export function ordersListRequestToJSON(
  ordersListRequest: OrdersListRequest,
): string {
  return JSON.stringify(
    OrdersListRequest$outboundSchema.parse(ordersListRequest),
  );
}

export function ordersListRequestFromJSON(
  jsonString: string,
): SafeParseResult<OrdersListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrdersListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersListRequest' from JSON`,
  );
}

/** @internal */
export const OrdersListResponse$inboundSchema: z.ZodType<
  OrdersListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: ListResourceOrder$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type OrdersListResponse$Outbound = {
  Result: ListResourceOrder$Outbound;
};

/** @internal */
export const OrdersListResponse$outboundSchema: z.ZodType<
  OrdersListResponse$Outbound,
  z.ZodTypeDef,
  OrdersListResponse
> = z.object({
  result: ListResourceOrder$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrdersListResponse$ {
  /** @deprecated use `OrdersListResponse$inboundSchema` instead. */
  export const inboundSchema = OrdersListResponse$inboundSchema;
  /** @deprecated use `OrdersListResponse$outboundSchema` instead. */
  export const outboundSchema = OrdersListResponse$outboundSchema;
  /** @deprecated use `OrdersListResponse$Outbound` instead. */
  export type Outbound = OrdersListResponse$Outbound;
}

export function ordersListResponseToJSON(
  ordersListResponse: OrdersListResponse,
): string {
  return JSON.stringify(
    OrdersListResponse$outboundSchema.parse(ordersListResponse),
  );
}

export function ordersListResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrdersListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrdersListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrdersListResponse' from JSON`,
  );
}
