/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type OrdersGetRequest = {
  /**
   * The order ID.
   */
  id: string;
};

/** @internal */
export type OrdersGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const OrdersGetRequest$outboundSchema: z.ZodType<
  OrdersGetRequest$Outbound,
  z.ZodTypeDef,
  OrdersGetRequest
> = z.object({
  id: z.string(),
});

export function ordersGetRequestToJSON(
  ordersGetRequest: OrdersGetRequest,
): string {
  return JSON.stringify(
    OrdersGetRequest$outboundSchema.parse(ordersGetRequest),
  );
}
