/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

/**
 * Filter by platform.
 */
export type QueryParamPlatformFilter =
  | components.Platforms
  | Array<components.Platforms>;

/**
 * Filter by name.
 */
export type QueryParamRepositoryNameFilter = string | Array<string>;

/**
 * Filter by external organization name.
 */
export type ExternalOrganizationNameFilter = string | Array<string>;

/**
 * Filter by organization ID.
 */
export type RepositoriesListQueryParamOrganizationIDFilter =
  | string
  | Array<string>;

export type RepositoriesListRequest = {
  /**
   * Filter by platform.
   */
  platform?:
    | components.Platforms
    | Array<components.Platforms>
    | null
    | undefined;
  /**
   * Filter by name.
   */
  name?: string | Array<string> | null | undefined;
  /**
   * Filter by external organization name.
   */
  externalOrganizationName?: string | Array<string> | null | undefined;
  /**
   * Filter by private status.
   */
  isPrivate?: boolean | null | undefined;
  /**
   * Filter by organization ID.
   */
  organizationId?: string | Array<string> | null | undefined;
  /**
   * Page number, defaults to 1.
   */
  page?: number | undefined;
  /**
   * Size of a page, defaults to 10. Maximum is 100.
   */
  limit?: number | undefined;
  /**
   * Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
   */
  sorting?: Array<components.RepositorySortProperty> | null | undefined;
};

export type RepositoriesListResponse = {
  result: components.ListResourceRepository;
};

/** @internal */
export const QueryParamPlatformFilter$inboundSchema: z.ZodType<
  QueryParamPlatformFilter,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.Platforms$inboundSchema,
  z.array(components.Platforms$inboundSchema),
]);

/** @internal */
export type QueryParamPlatformFilter$Outbound = string | Array<string>;

/** @internal */
export const QueryParamPlatformFilter$outboundSchema: z.ZodType<
  QueryParamPlatformFilter$Outbound,
  z.ZodTypeDef,
  QueryParamPlatformFilter
> = z.union([
  components.Platforms$outboundSchema,
  z.array(components.Platforms$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryParamPlatformFilter$ {
  /** @deprecated use `QueryParamPlatformFilter$inboundSchema` instead. */
  export const inboundSchema = QueryParamPlatformFilter$inboundSchema;
  /** @deprecated use `QueryParamPlatformFilter$outboundSchema` instead. */
  export const outboundSchema = QueryParamPlatformFilter$outboundSchema;
  /** @deprecated use `QueryParamPlatformFilter$Outbound` instead. */
  export type Outbound = QueryParamPlatformFilter$Outbound;
}

/** @internal */
export const QueryParamRepositoryNameFilter$inboundSchema: z.ZodType<
  QueryParamRepositoryNameFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type QueryParamRepositoryNameFilter$Outbound = string | Array<string>;

/** @internal */
export const QueryParamRepositoryNameFilter$outboundSchema: z.ZodType<
  QueryParamRepositoryNameFilter$Outbound,
  z.ZodTypeDef,
  QueryParamRepositoryNameFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryParamRepositoryNameFilter$ {
  /** @deprecated use `QueryParamRepositoryNameFilter$inboundSchema` instead. */
  export const inboundSchema = QueryParamRepositoryNameFilter$inboundSchema;
  /** @deprecated use `QueryParamRepositoryNameFilter$outboundSchema` instead. */
  export const outboundSchema = QueryParamRepositoryNameFilter$outboundSchema;
  /** @deprecated use `QueryParamRepositoryNameFilter$Outbound` instead. */
  export type Outbound = QueryParamRepositoryNameFilter$Outbound;
}

/** @internal */
export const ExternalOrganizationNameFilter$inboundSchema: z.ZodType<
  ExternalOrganizationNameFilter,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type ExternalOrganizationNameFilter$Outbound = string | Array<string>;

/** @internal */
export const ExternalOrganizationNameFilter$outboundSchema: z.ZodType<
  ExternalOrganizationNameFilter$Outbound,
  z.ZodTypeDef,
  ExternalOrganizationNameFilter
> = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExternalOrganizationNameFilter$ {
  /** @deprecated use `ExternalOrganizationNameFilter$inboundSchema` instead. */
  export const inboundSchema = ExternalOrganizationNameFilter$inboundSchema;
  /** @deprecated use `ExternalOrganizationNameFilter$outboundSchema` instead. */
  export const outboundSchema = ExternalOrganizationNameFilter$outboundSchema;
  /** @deprecated use `ExternalOrganizationNameFilter$Outbound` instead. */
  export type Outbound = ExternalOrganizationNameFilter$Outbound;
}

/** @internal */
export const RepositoriesListQueryParamOrganizationIDFilter$inboundSchema:
  z.ZodType<
    RepositoriesListQueryParamOrganizationIDFilter,
    z.ZodTypeDef,
    unknown
  > = z.union([z.string(), z.array(z.string())]);

/** @internal */
export type RepositoriesListQueryParamOrganizationIDFilter$Outbound =
  | string
  | Array<string>;

/** @internal */
export const RepositoriesListQueryParamOrganizationIDFilter$outboundSchema:
  z.ZodType<
    RepositoriesListQueryParamOrganizationIDFilter$Outbound,
    z.ZodTypeDef,
    RepositoriesListQueryParamOrganizationIDFilter
  > = z.union([z.string(), z.array(z.string())]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositoriesListQueryParamOrganizationIDFilter$ {
  /** @deprecated use `RepositoriesListQueryParamOrganizationIDFilter$inboundSchema` instead. */
  export const inboundSchema =
    RepositoriesListQueryParamOrganizationIDFilter$inboundSchema;
  /** @deprecated use `RepositoriesListQueryParamOrganizationIDFilter$outboundSchema` instead. */
  export const outboundSchema =
    RepositoriesListQueryParamOrganizationIDFilter$outboundSchema;
  /** @deprecated use `RepositoriesListQueryParamOrganizationIDFilter$Outbound` instead. */
  export type Outbound =
    RepositoriesListQueryParamOrganizationIDFilter$Outbound;
}

/** @internal */
export const RepositoriesListRequest$inboundSchema: z.ZodType<
  RepositoriesListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  platform: z.nullable(
    z.union([
      components.Platforms$inboundSchema,
      z.array(components.Platforms$inboundSchema),
    ]),
  ).optional(),
  name: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  external_organization_name: z.nullable(
    z.union([z.string(), z.array(z.string())]),
  ).optional(),
  is_private: z.nullable(z.boolean()).optional(),
  organization_id: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  sorting: z.nullable(z.array(components.RepositorySortProperty$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "external_organization_name": "externalOrganizationName",
    "is_private": "isPrivate",
    "organization_id": "organizationId",
  });
});

/** @internal */
export type RepositoriesListRequest$Outbound = {
  platform?: string | Array<string> | null | undefined;
  name?: string | Array<string> | null | undefined;
  external_organization_name?: string | Array<string> | null | undefined;
  is_private?: boolean | null | undefined;
  organization_id?: string | Array<string> | null | undefined;
  page: number;
  limit: number;
  sorting?: Array<string> | null | undefined;
};

/** @internal */
export const RepositoriesListRequest$outboundSchema: z.ZodType<
  RepositoriesListRequest$Outbound,
  z.ZodTypeDef,
  RepositoriesListRequest
> = z.object({
  platform: z.nullable(
    z.union([
      components.Platforms$outboundSchema,
      z.array(components.Platforms$outboundSchema),
    ]),
  ).optional(),
  name: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
  externalOrganizationName: z.nullable(
    z.union([z.string(), z.array(z.string())]),
  ).optional(),
  isPrivate: z.nullable(z.boolean()).optional(),
  organizationId: z.nullable(z.union([z.string(), z.array(z.string())]))
    .optional(),
  page: z.number().int().default(1),
  limit: z.number().int().default(10),
  sorting: z.nullable(z.array(components.RepositorySortProperty$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    externalOrganizationName: "external_organization_name",
    isPrivate: "is_private",
    organizationId: "organization_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositoriesListRequest$ {
  /** @deprecated use `RepositoriesListRequest$inboundSchema` instead. */
  export const inboundSchema = RepositoriesListRequest$inboundSchema;
  /** @deprecated use `RepositoriesListRequest$outboundSchema` instead. */
  export const outboundSchema = RepositoriesListRequest$outboundSchema;
  /** @deprecated use `RepositoriesListRequest$Outbound` instead. */
  export type Outbound = RepositoriesListRequest$Outbound;
}

/** @internal */
export const RepositoriesListResponse$inboundSchema: z.ZodType<
  RepositoriesListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ListResourceRepository$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type RepositoriesListResponse$Outbound = {
  Result: components.ListResourceRepository$Outbound;
};

/** @internal */
export const RepositoriesListResponse$outboundSchema: z.ZodType<
  RepositoriesListResponse$Outbound,
  z.ZodTypeDef,
  RepositoriesListResponse
> = z.object({
  result: components.ListResourceRepository$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RepositoriesListResponse$ {
  /** @deprecated use `RepositoriesListResponse$inboundSchema` instead. */
  export const inboundSchema = RepositoriesListResponse$inboundSchema;
  /** @deprecated use `RepositoriesListResponse$outboundSchema` instead. */
  export const outboundSchema = RepositoriesListResponse$outboundSchema;
  /** @deprecated use `RepositoriesListResponse$Outbound` instead. */
  export type Outbound = RepositoriesListResponse$Outbound;
}
