/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CountryAlpha2Input = {
  Bh: "BH",
  Ci: "CI",
  Cw: "CW",
  Bs: "BS",
  Re: "RE",
  Gd: "GD",
  Tn: "TN",
  Nc: "NC",
  Cc: "CC",
  Mg: "MG",
  Ve: "VE",
  Gy: "GY",
  Dj: "DJ",
  Sj: "SJ",
  Tm: "TM",
  Sg: "SG",
  Ao: "AO",
  Id: "ID",
  Jm: "JM",
  Jo: "JO",
  Gg: "GG",
  Fm: "FM",
  Bo: "BO",
  Nu: "NU",
  Si: "SI",
  Bv: "BV",
  Cm: "CM",
  La: "LA",
  Kg: "KG",
  Lc: "LC",
  Mv: "MV",
  Tt: "TT",
  To: "TO",
  Gb: "GB",
  Ug: "UG",
  Tr: "TR",
  Ai: "AI",
  Sh: "SH",
  Bf: "BF",
  It: "IT",
  Kw: "KW",
  Tw: "TW",
  Hk: "HK",
  Aw: "AW",
  Lb: "LB",
  Ly: "LY",
  Vi: "VI",
  Cd: "CD",
  Es: "ES",
  Pa: "PA",
  Mn: "MN",
  Ms: "MS",
  Vg: "VG",
  Sa: "SA",
  Bt: "BT",
  Er: "ER",
  Ua: "UA",
  Hn: "HN",
  Ag: "AG",
  Vn: "VN",
  Ma: "MA",
  Pg: "PG",
  Th: "TH",
  Ee: "EE",
  Mu: "MU",
  Cr: "CR",
  Ge: "GE",
  Gr: "GR",
  Mr: "MR",
  Zw: "ZW",
  Tc: "TC",
  Ck: "CK",
  Gw: "GW",
  Hr: "HR",
  Lt: "LT",
  Qa: "QA",
  Mo: "MO",
  Ad: "AD",
  Fr: "FR",
  Km: "KM",
  Gs: "GS",
  Bg: "BG",
  Ng: "NG",
  As: "AS",
  Za: "ZA",
  Pt: "PT",
  Np: "NP",
  Rw: "RW",
  Gl: "GL",
  Rs: "RS",
  Mq: "MQ",
  Cv: "CV",
  Gq: "GQ",
  Mf: "MF",
  Mh: "MH",
  Gp: "GP",
  Kn: "KN",
  Wf: "WF",
  Fj: "FJ",
  Fk: "FK",
  Me: "ME",
  Ne: "NE",
  Gm: "GM",
  Gh: "GH",
  Sv: "SV",
  Hm: "HM",
  Bn: "BN",
  Ga: "GA",
  Py: "PY",
  Bl: "BL",
  Eg: "EG",
  Se: "SE",
  Fo: "FO",
  Va: "VA",
  Tk: "TK",
  Ye: "YE",
  Dm: "DM",
  Nl: "NL",
  Mk: "MK",
  Uz: "UZ",
  In: "IN",
  Tl: "TL",
  Iq: "IQ",
  Bz: "BZ",
  Mc: "MC",
  Bj: "BJ",
  Ae: "AE",
  Pn: "PN",
  Ke: "KE",
  Cx: "CX",
  Aq: "AQ",
  Eh: "EH",
  St: "ST",
  Mz: "MZ",
  Sc: "SC",
  Sm: "SM",
  Im: "IM",
  Tj: "TJ",
  Ps: "PS",
  Mt: "MT",
  Sk: "SK",
  By: "BY",
  Il: "IL",
  Cy: "CY",
  Bm: "BM",
  Sr: "SR",
  Am: "AM",
  Pe: "PE",
  Ws: "WS",
  Fi: "FI",
  Li: "LI",
  No: "NO",
  Gf: "GF",
  Nr: "NR",
  Bi: "BI",
  Sd: "SD",
  Mp: "MP",
  Je: "JE",
  Ca: "CA",
  Ec: "EC",
  Hu: "HU",
  So: "SO",
  Tz: "TZ",
  Cn: "CN",
  Vc: "VC",
  Sz: "SZ",
  Ml: "ML",
  Bd: "BD",
  Gn: "GN",
  Ki: "KI",
  Do: "DO",
  Sx: "SX",
  Um: "UM",
  Cf: "CF",
  Pw: "PW",
  Zm: "ZM",
  Tf: "TF",
  Tg: "TG",
  Is: "IS",
  Yt: "YT",
  De: "DE",
  Dz: "DZ",
  Uy: "UY",
  Af: "AF",
  Be: "BE",
  Kz: "KZ",
  Nz: "NZ",
  Pl: "PL",
  Pf: "PF",
  At: "AT",
  Az: "AZ",
  Br: "BR",
  Gi: "GI",
  Td: "TD",
  Co: "CO",
  Et: "ET",
  Md: "MD",
  Mw: "MW",
  Om: "OM",
  Ph: "PH",
  Ie: "IE",
  Kr: "KR",
  Pk: "PK",
  Au: "AU",
  Ni: "NI",
  Ro: "RO",
  Lu: "LU",
  Mx: "MX",
  Ar: "AR",
  Na: "NA",
  Dk: "DK",
  Mm: "MM",
  Ax: "AX",
  Ch: "CH",
  Nf: "NF",
  Lr: "LR",
  Sn: "SN",
  Gu: "GU",
  Cl: "CL",
  Pm: "PM",
  Us: "US",
  Gt: "GT",
  Al: "AL",
  Vu: "VU",
  Pr: "PR",
  Sb: "SB",
  Ss: "SS",
  Jp: "JP",
  Kh: "KH",
  Ls: "LS",
  Sl: "SL",
  Ky: "KY",
  Io: "IO",
  Bb: "BB",
  Ht: "HT",
  Cz: "CZ",
  Lv: "LV",
  Ba: "BA",
  My: "MY",
  Bw: "BW",
  Tv: "TV",
  Bq: "BQ",
  Lk: "LK",
  Cg: "CG",
} as const;
export type CountryAlpha2Input = ClosedEnum<typeof CountryAlpha2Input>;

export type AddressInput = {
  line1?: string | null | undefined;
  line2?: string | null | undefined;
  postalCode?: string | null | undefined;
  city?: string | null | undefined;
  state?: string | null | undefined;
  country: CountryAlpha2Input;
};

/** @internal */
export const CountryAlpha2Input$inboundSchema: z.ZodNativeEnum<
  typeof CountryAlpha2Input
> = z.nativeEnum(CountryAlpha2Input);

/** @internal */
export const CountryAlpha2Input$outboundSchema: z.ZodNativeEnum<
  typeof CountryAlpha2Input
> = CountryAlpha2Input$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountryAlpha2Input$ {
  /** @deprecated use `CountryAlpha2Input$inboundSchema` instead. */
  export const inboundSchema = CountryAlpha2Input$inboundSchema;
  /** @deprecated use `CountryAlpha2Input$outboundSchema` instead. */
  export const outboundSchema = CountryAlpha2Input$outboundSchema;
}

/** @internal */
export const AddressInput$inboundSchema: z.ZodType<
  AddressInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  line1: z.nullable(z.string()).optional(),
  line2: z.nullable(z.string()).optional(),
  postal_code: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  country: CountryAlpha2Input$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "postal_code": "postalCode",
  });
});

/** @internal */
export type AddressInput$Outbound = {
  line1?: string | null | undefined;
  line2?: string | null | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  state?: string | null | undefined;
  country: string;
};

/** @internal */
export const AddressInput$outboundSchema: z.ZodType<
  AddressInput$Outbound,
  z.ZodTypeDef,
  AddressInput
> = z.object({
  line1: z.nullable(z.string()).optional(),
  line2: z.nullable(z.string()).optional(),
  postalCode: z.nullable(z.string()).optional(),
  city: z.nullable(z.string()).optional(),
  state: z.nullable(z.string()).optional(),
  country: CountryAlpha2Input$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    postalCode: "postal_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressInput$ {
  /** @deprecated use `AddressInput$inboundSchema` instead. */
  export const inboundSchema = AddressInput$inboundSchema;
  /** @deprecated use `AddressInput$outboundSchema` instead. */
  export const outboundSchema = AddressInput$outboundSchema;
  /** @deprecated use `AddressInput$Outbound` instead. */
  export type Outbound = AddressInput$Outbound;
}

export function addressInputToJSON(addressInput: AddressInput): string {
  return JSON.stringify(AddressInput$outboundSchema.parse(addressInput));
}

export function addressInputFromJSON(
  jsonString: string,
): SafeParseResult<AddressInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressInput' from JSON`,
  );
}
