/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ArticleVisibility = {
  Public: "public",
  Hidden: "hidden",
  Private: "private",
} as const;
export type ArticleVisibility = ClosedEnum<typeof ArticleVisibility>;

/** @internal */
export const ArticleVisibility$inboundSchema: z.ZodNativeEnum<
  typeof ArticleVisibility
> = z.nativeEnum(ArticleVisibility);

/** @internal */
export const ArticleVisibility$outboundSchema: z.ZodNativeEnum<
  typeof ArticleVisibility
> = ArticleVisibility$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ArticleVisibility$ {
  /** @deprecated use `ArticleVisibility$inboundSchema` instead. */
  export const inboundSchema = ArticleVisibility$inboundSchema;
  /** @deprecated use `ArticleVisibility$outboundSchema` instead. */
  export const outboundSchema = ArticleVisibility$outboundSchema;
}
