/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BenefitMeterCreditProperties,
  BenefitMeterCreditProperties$inboundSchema,
  BenefitMeterCreditProperties$Outbound,
  BenefitMeterCreditProperties$outboundSchema,
} from "./benefitmetercreditproperties.js";

/**
 * A benefit of type `meter_unit`.
 *
 * @remarks
 *
 * Use it to grant a number of units on a specific meter.
 */
export type BenefitMeterCredit = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the benefit.
   */
  id: string;
  type?: "meter_credit" | undefined;
  /**
   * The description of the benefit.
   */
  description: string;
  /**
   * Whether the benefit is selectable when creating a product.
   */
  selectable: boolean;
  /**
   * Whether the benefit is deletable.
   */
  deletable: boolean;
  /**
   * The ID of the organization owning the benefit.
   */
  organizationId: string;
  /**
   * Properties for a benefit of type `meter_unit`.
   */
  properties: BenefitMeterCreditProperties;
};

/** @internal */
export const BenefitMeterCredit$inboundSchema: z.ZodType<
  BenefitMeterCredit,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  modified_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  id: z.string(),
  type: z.literal("meter_credit").optional(),
  description: z.string(),
  selectable: z.boolean(),
  deletable: z.boolean(),
  organization_id: z.string(),
  properties: BenefitMeterCreditProperties$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "modified_at": "modifiedAt",
    "organization_id": "organizationId",
  });
});

/** @internal */
export type BenefitMeterCredit$Outbound = {
  created_at: string;
  modified_at: string | null;
  id: string;
  type: "meter_credit";
  description: string;
  selectable: boolean;
  deletable: boolean;
  organization_id: string;
  properties: BenefitMeterCreditProperties$Outbound;
};

/** @internal */
export const BenefitMeterCredit$outboundSchema: z.ZodType<
  BenefitMeterCredit$Outbound,
  z.ZodTypeDef,
  BenefitMeterCredit
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
  id: z.string(),
  type: z.literal("meter_credit").default("meter_credit" as const),
  description: z.string(),
  selectable: z.boolean(),
  deletable: z.boolean(),
  organizationId: z.string(),
  properties: BenefitMeterCreditProperties$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    modifiedAt: "modified_at",
    organizationId: "organization_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BenefitMeterCredit$ {
  /** @deprecated use `BenefitMeterCredit$inboundSchema` instead. */
  export const inboundSchema = BenefitMeterCredit$inboundSchema;
  /** @deprecated use `BenefitMeterCredit$outboundSchema` instead. */
  export const outboundSchema = BenefitMeterCredit$outboundSchema;
  /** @deprecated use `BenefitMeterCredit$Outbound` instead. */
  export type Outbound = BenefitMeterCredit$Outbound;
}

export function benefitMeterCreditToJSON(
  benefitMeterCredit: BenefitMeterCredit,
): string {
  return JSON.stringify(
    BenefitMeterCredit$outboundSchema.parse(benefitMeterCredit),
  );
}

export function benefitMeterCreditFromJSON(
  jsonString: string,
): SafeParseResult<BenefitMeterCredit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BenefitMeterCredit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BenefitMeterCredit' from JSON`,
  );
}
