/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BenefitLicenseKeyActivationProperties = {
  limit: number;
  enableCustomerAdmin: boolean;
};

/** @internal */
export const BenefitLicenseKeyActivationProperties$inboundSchema: z.ZodType<
  BenefitLicenseKeyActivationProperties,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  enable_customer_admin: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "enable_customer_admin": "enableCustomerAdmin",
  });
});
/** @internal */
export type BenefitLicenseKeyActivationProperties$Outbound = {
  limit: number;
  enable_customer_admin: boolean;
};

/** @internal */
export const BenefitLicenseKeyActivationProperties$outboundSchema: z.ZodType<
  BenefitLicenseKeyActivationProperties$Outbound,
  z.ZodTypeDef,
  BenefitLicenseKeyActivationProperties
> = z.object({
  limit: z.number().int(),
  enableCustomerAdmin: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    enableCustomerAdmin: "enable_customer_admin",
  });
});

export function benefitLicenseKeyActivationPropertiesToJSON(
  benefitLicenseKeyActivationProperties: BenefitLicenseKeyActivationProperties,
): string {
  return JSON.stringify(
    BenefitLicenseKeyActivationProperties$outboundSchema.parse(
      benefitLicenseKeyActivationProperties,
    ),
  );
}
export function benefitLicenseKeyActivationPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<BenefitLicenseKeyActivationProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BenefitLicenseKeyActivationProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BenefitLicenseKeyActivationProperties' from JSON`,
  );
}
