/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Address,
  Address$inboundSchema,
  Address$Outbound,
  Address$outboundSchema,
} from "./address.js";
import {
  AttachedCustomField,
  AttachedCustomField$inboundSchema,
  AttachedCustomField$Outbound,
  AttachedCustomField$outboundSchema,
} from "./attachedcustomfield.js";
import {
  CheckoutBillingAddressFields,
  CheckoutBillingAddressFields$inboundSchema,
  CheckoutBillingAddressFields$Outbound,
  CheckoutBillingAddressFields$outboundSchema,
} from "./checkoutbillingaddressfields.js";
import {
  CheckoutDiscountFixedOnceForeverDuration,
  CheckoutDiscountFixedOnceForeverDuration$inboundSchema,
  CheckoutDiscountFixedOnceForeverDuration$Outbound,
  CheckoutDiscountFixedOnceForeverDuration$outboundSchema,
} from "./checkoutdiscountfixedonceforeverduration.js";
import {
  CheckoutDiscountFixedRepeatDuration,
  CheckoutDiscountFixedRepeatDuration$inboundSchema,
  CheckoutDiscountFixedRepeatDuration$Outbound,
  CheckoutDiscountFixedRepeatDuration$outboundSchema,
} from "./checkoutdiscountfixedrepeatduration.js";
import {
  CheckoutDiscountPercentageOnceForeverDuration,
  CheckoutDiscountPercentageOnceForeverDuration$inboundSchema,
  CheckoutDiscountPercentageOnceForeverDuration$Outbound,
  CheckoutDiscountPercentageOnceForeverDuration$outboundSchema,
} from "./checkoutdiscountpercentageonceforeverduration.js";
import {
  CheckoutDiscountPercentageRepeatDuration,
  CheckoutDiscountPercentageRepeatDuration$inboundSchema,
  CheckoutDiscountPercentageRepeatDuration$Outbound,
  CheckoutDiscountPercentageRepeatDuration$outboundSchema,
} from "./checkoutdiscountpercentagerepeatduration.js";
import {
  CheckoutProduct,
  CheckoutProduct$inboundSchema,
  CheckoutProduct$Outbound,
  CheckoutProduct$outboundSchema,
} from "./checkoutproduct.js";
import {
  LegacyRecurringProductPrice,
  LegacyRecurringProductPrice$inboundSchema,
  LegacyRecurringProductPrice$Outbound,
  LegacyRecurringProductPrice$outboundSchema,
} from "./legacyrecurringproductprice.js";
import {
  Organization,
  Organization$inboundSchema,
  Organization$Outbound,
  Organization$outboundSchema,
} from "./organization.js";
import {
  PaymentProcessor,
  PaymentProcessor$inboundSchema,
  PaymentProcessor$outboundSchema,
} from "./paymentprocessor.js";
import {
  ProductPrice,
  ProductPrice$inboundSchema,
  ProductPrice$Outbound,
  ProductPrice$outboundSchema,
} from "./productprice.js";

export type CheckoutPublicConfirmedCustomFieldData =
  | string
  | number
  | boolean
  | Date;

/**
 * Price of the selected product.
 */
export type CheckoutPublicConfirmedProductPrice =
  | LegacyRecurringProductPrice
  | ProductPrice;

export type CheckoutPublicConfirmedDiscount =
  | CheckoutDiscountFixedRepeatDuration
  | CheckoutDiscountFixedOnceForeverDuration
  | CheckoutDiscountPercentageRepeatDuration
  | CheckoutDiscountPercentageOnceForeverDuration;

/**
 * Checkout session data retrieved using the client secret after confirmation.
 *
 * @remarks
 *
 * It contains a customer session token to retrieve order information
 * right after the checkout.
 */
export type CheckoutPublicConfirmed = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the object.
   */
  id: string;
  /**
   * Key-value object storing custom field values.
   */
  customFieldData?:
    | { [k: string]: string | number | boolean | Date | null }
    | undefined;
  paymentProcessor: PaymentProcessor;
  status: "confirmed";
  /**
   * Client secret used to update and complete the checkout session from the client.
   */
  clientSecret: string;
  /**
   * URL where the customer can access the checkout session.
   */
  url: string;
  /**
   * Expiration date and time of the checkout session.
   */
  expiresAt: Date;
  /**
   * URL where the customer will be redirected after a successful payment.
   */
  successUrl: string;
  /**
   * When checkout is embedded, represents the Origin of the page embedding the checkout. Used as a security measure to send messages only to the embedding page.
   */
  embedOrigin: string | null;
  /**
   * Amount in cents, before discounts and taxes.
   */
  amount: number;
  /**
   * Discount amount in cents.
   */
  discountAmount: number;
  /**
   * Amount in cents, after discounts but before taxes.
   */
  netAmount: number;
  /**
   * Sales tax amount in cents. If `null`, it means there is no enough information yet to calculate it.
   */
  taxAmount: number | null;
  /**
   * Amount in cents, after discounts and taxes.
   */
  totalAmount: number;
  /**
   * Currency code of the checkout session.
   */
  currency: string;
  /**
   * ID of the product to checkout.
   */
  productId: string;
  /**
   * ID of the product price to checkout.
   */
  productPriceId: string;
  /**
   * ID of the discount applied to the checkout.
   */
  discountId: string | null;
  /**
   * Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.
   */
  allowDiscountCodes: boolean;
  /**
   * Whether to require the customer to fill their full billing address, instead of just the country. Customers in the US will always be required to fill their full address, regardless of this setting. If you preset the billing address, this setting will be automatically set to `true`.
   */
  requireBillingAddress: boolean;
  /**
   * Whether the discount is applicable to the checkout. Typically, free and custom prices are not discountable.
   */
  isDiscountApplicable: boolean;
  /**
   * Whether the product price is free, regardless of discounts.
   */
  isFreeProductPrice: boolean;
  /**
   * Whether the checkout requires payment, e.g. in case of free products or discounts that cover the total amount.
   */
  isPaymentRequired: boolean;
  /**
   * Whether the checkout requires setting up a payment method, regardless of the amount, e.g. subscriptions that have first free cycles.
   */
  isPaymentSetupRequired: boolean;
  /**
   * Whether the checkout requires a payment form, whether because of a payment or payment method setup.
   */
  isPaymentFormRequired: boolean;
  customerId: string | null;
  /**
   * Whether the customer is a business or an individual. If `true`, the customer will be required to fill their full billing address and billing name.
   */
  isBusinessCustomer: boolean;
  /**
   * Name of the customer.
   */
  customerName: string | null;
  /**
   * Email address of the customer.
   */
  customerEmail: string | null;
  customerIpAddress: string | null;
  customerBillingName: string | null;
  customerBillingAddress: Address | null;
  customerTaxId: string | null;
  paymentProcessorMetadata: { [k: string]: string };
  billingAddressFields: CheckoutBillingAddressFields;
  /**
   * List of products available to select.
   */
  products: Array<CheckoutProduct>;
  /**
   * Product data for a checkout session.
   */
  product: CheckoutProduct;
  /**
   * Price of the selected product.
   */
  productPrice: LegacyRecurringProductPrice | ProductPrice;
  discount:
    | CheckoutDiscountFixedRepeatDuration
    | CheckoutDiscountFixedOnceForeverDuration
    | CheckoutDiscountPercentageRepeatDuration
    | CheckoutDiscountPercentageOnceForeverDuration
    | null;
  organization: Organization;
  attachedCustomFields: Array<AttachedCustomField>;
  customerSessionToken: string;
};

/** @internal */
export const CheckoutPublicConfirmedCustomFieldData$inboundSchema: z.ZodType<
  CheckoutPublicConfirmedCustomFieldData,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number().int(),
  z.boolean(),
  z.string().datetime({ offset: true }).transform(v => new Date(v)),
]);

/** @internal */
export type CheckoutPublicConfirmedCustomFieldData$Outbound =
  | string
  | number
  | boolean
  | string;

/** @internal */
export const CheckoutPublicConfirmedCustomFieldData$outboundSchema: z.ZodType<
  CheckoutPublicConfirmedCustomFieldData$Outbound,
  z.ZodTypeDef,
  CheckoutPublicConfirmedCustomFieldData
> = z.union([
  z.string(),
  z.number().int(),
  z.boolean(),
  z.date().transform(v => v.toISOString()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutPublicConfirmedCustomFieldData$ {
  /** @deprecated use `CheckoutPublicConfirmedCustomFieldData$inboundSchema` instead. */
  export const inboundSchema =
    CheckoutPublicConfirmedCustomFieldData$inboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedCustomFieldData$outboundSchema` instead. */
  export const outboundSchema =
    CheckoutPublicConfirmedCustomFieldData$outboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedCustomFieldData$Outbound` instead. */
  export type Outbound = CheckoutPublicConfirmedCustomFieldData$Outbound;
}

export function checkoutPublicConfirmedCustomFieldDataToJSON(
  checkoutPublicConfirmedCustomFieldData:
    CheckoutPublicConfirmedCustomFieldData,
): string {
  return JSON.stringify(
    CheckoutPublicConfirmedCustomFieldData$outboundSchema.parse(
      checkoutPublicConfirmedCustomFieldData,
    ),
  );
}

export function checkoutPublicConfirmedCustomFieldDataFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutPublicConfirmedCustomFieldData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CheckoutPublicConfirmedCustomFieldData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutPublicConfirmedCustomFieldData' from JSON`,
  );
}

/** @internal */
export const CheckoutPublicConfirmedProductPrice$inboundSchema: z.ZodType<
  CheckoutPublicConfirmedProductPrice,
  z.ZodTypeDef,
  unknown
> = z.union([
  LegacyRecurringProductPrice$inboundSchema,
  ProductPrice$inboundSchema,
]);

/** @internal */
export type CheckoutPublicConfirmedProductPrice$Outbound =
  | LegacyRecurringProductPrice$Outbound
  | ProductPrice$Outbound;

/** @internal */
export const CheckoutPublicConfirmedProductPrice$outboundSchema: z.ZodType<
  CheckoutPublicConfirmedProductPrice$Outbound,
  z.ZodTypeDef,
  CheckoutPublicConfirmedProductPrice
> = z.union([
  LegacyRecurringProductPrice$outboundSchema,
  ProductPrice$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutPublicConfirmedProductPrice$ {
  /** @deprecated use `CheckoutPublicConfirmedProductPrice$inboundSchema` instead. */
  export const inboundSchema =
    CheckoutPublicConfirmedProductPrice$inboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedProductPrice$outboundSchema` instead. */
  export const outboundSchema =
    CheckoutPublicConfirmedProductPrice$outboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedProductPrice$Outbound` instead. */
  export type Outbound = CheckoutPublicConfirmedProductPrice$Outbound;
}

export function checkoutPublicConfirmedProductPriceToJSON(
  checkoutPublicConfirmedProductPrice: CheckoutPublicConfirmedProductPrice,
): string {
  return JSON.stringify(
    CheckoutPublicConfirmedProductPrice$outboundSchema.parse(
      checkoutPublicConfirmedProductPrice,
    ),
  );
}

export function checkoutPublicConfirmedProductPriceFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutPublicConfirmedProductPrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CheckoutPublicConfirmedProductPrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutPublicConfirmedProductPrice' from JSON`,
  );
}

/** @internal */
export const CheckoutPublicConfirmedDiscount$inboundSchema: z.ZodType<
  CheckoutPublicConfirmedDiscount,
  z.ZodTypeDef,
  unknown
> = z.union([
  CheckoutDiscountFixedRepeatDuration$inboundSchema,
  CheckoutDiscountFixedOnceForeverDuration$inboundSchema,
  CheckoutDiscountPercentageRepeatDuration$inboundSchema,
  CheckoutDiscountPercentageOnceForeverDuration$inboundSchema,
]);

/** @internal */
export type CheckoutPublicConfirmedDiscount$Outbound =
  | CheckoutDiscountFixedRepeatDuration$Outbound
  | CheckoutDiscountFixedOnceForeverDuration$Outbound
  | CheckoutDiscountPercentageRepeatDuration$Outbound
  | CheckoutDiscountPercentageOnceForeverDuration$Outbound;

/** @internal */
export const CheckoutPublicConfirmedDiscount$outboundSchema: z.ZodType<
  CheckoutPublicConfirmedDiscount$Outbound,
  z.ZodTypeDef,
  CheckoutPublicConfirmedDiscount
> = z.union([
  CheckoutDiscountFixedRepeatDuration$outboundSchema,
  CheckoutDiscountFixedOnceForeverDuration$outboundSchema,
  CheckoutDiscountPercentageRepeatDuration$outboundSchema,
  CheckoutDiscountPercentageOnceForeverDuration$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutPublicConfirmedDiscount$ {
  /** @deprecated use `CheckoutPublicConfirmedDiscount$inboundSchema` instead. */
  export const inboundSchema = CheckoutPublicConfirmedDiscount$inboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedDiscount$outboundSchema` instead. */
  export const outboundSchema = CheckoutPublicConfirmedDiscount$outboundSchema;
  /** @deprecated use `CheckoutPublicConfirmedDiscount$Outbound` instead. */
  export type Outbound = CheckoutPublicConfirmedDiscount$Outbound;
}

export function checkoutPublicConfirmedDiscountToJSON(
  checkoutPublicConfirmedDiscount: CheckoutPublicConfirmedDiscount,
): string {
  return JSON.stringify(
    CheckoutPublicConfirmedDiscount$outboundSchema.parse(
      checkoutPublicConfirmedDiscount,
    ),
  );
}

export function checkoutPublicConfirmedDiscountFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutPublicConfirmedDiscount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckoutPublicConfirmedDiscount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutPublicConfirmedDiscount' from JSON`,
  );
}

/** @internal */
export const CheckoutPublicConfirmed$inboundSchema: z.ZodType<
  CheckoutPublicConfirmed,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  modified_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  id: z.string(),
  custom_field_data: z.record(
    z.nullable(
      z.union([
        z.string(),
        z.number().int(),
        z.boolean(),
        z.string().datetime({ offset: true }).transform(v => new Date(v)),
      ]),
    ),
  ).optional(),
  payment_processor: PaymentProcessor$inboundSchema,
  status: z.literal("confirmed"),
  client_secret: z.string(),
  url: z.string(),
  expires_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  success_url: z.string(),
  embed_origin: z.nullable(z.string()),
  amount: z.number().int(),
  discount_amount: z.number().int(),
  net_amount: z.number().int(),
  tax_amount: z.nullable(z.number().int()),
  total_amount: z.number().int(),
  currency: z.string(),
  product_id: z.string(),
  product_price_id: z.string(),
  discount_id: z.nullable(z.string()),
  allow_discount_codes: z.boolean(),
  require_billing_address: z.boolean(),
  is_discount_applicable: z.boolean(),
  is_free_product_price: z.boolean(),
  is_payment_required: z.boolean(),
  is_payment_setup_required: z.boolean(),
  is_payment_form_required: z.boolean(),
  customer_id: z.nullable(z.string()),
  is_business_customer: z.boolean(),
  customer_name: z.nullable(z.string()),
  customer_email: z.nullable(z.string()),
  customer_ip_address: z.nullable(z.string()),
  customer_billing_name: z.nullable(z.string()),
  customer_billing_address: z.nullable(Address$inboundSchema),
  customer_tax_id: z.nullable(z.string()),
  payment_processor_metadata: z.record(z.string()),
  billing_address_fields: CheckoutBillingAddressFields$inboundSchema,
  products: z.array(CheckoutProduct$inboundSchema),
  product: CheckoutProduct$inboundSchema,
  product_price: z.union([
    LegacyRecurringProductPrice$inboundSchema,
    ProductPrice$inboundSchema,
  ]),
  discount: z.nullable(
    z.union([
      CheckoutDiscountFixedRepeatDuration$inboundSchema,
      CheckoutDiscountFixedOnceForeverDuration$inboundSchema,
      CheckoutDiscountPercentageRepeatDuration$inboundSchema,
      CheckoutDiscountPercentageOnceForeverDuration$inboundSchema,
    ]),
  ),
  organization: Organization$inboundSchema,
  attached_custom_fields: z.array(AttachedCustomField$inboundSchema),
  customer_session_token: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "modified_at": "modifiedAt",
    "custom_field_data": "customFieldData",
    "payment_processor": "paymentProcessor",
    "client_secret": "clientSecret",
    "expires_at": "expiresAt",
    "success_url": "successUrl",
    "embed_origin": "embedOrigin",
    "discount_amount": "discountAmount",
    "net_amount": "netAmount",
    "tax_amount": "taxAmount",
    "total_amount": "totalAmount",
    "product_id": "productId",
    "product_price_id": "productPriceId",
    "discount_id": "discountId",
    "allow_discount_codes": "allowDiscountCodes",
    "require_billing_address": "requireBillingAddress",
    "is_discount_applicable": "isDiscountApplicable",
    "is_free_product_price": "isFreeProductPrice",
    "is_payment_required": "isPaymentRequired",
    "is_payment_setup_required": "isPaymentSetupRequired",
    "is_payment_form_required": "isPaymentFormRequired",
    "customer_id": "customerId",
    "is_business_customer": "isBusinessCustomer",
    "customer_name": "customerName",
    "customer_email": "customerEmail",
    "customer_ip_address": "customerIpAddress",
    "customer_billing_name": "customerBillingName",
    "customer_billing_address": "customerBillingAddress",
    "customer_tax_id": "customerTaxId",
    "payment_processor_metadata": "paymentProcessorMetadata",
    "billing_address_fields": "billingAddressFields",
    "product_price": "productPrice",
    "attached_custom_fields": "attachedCustomFields",
    "customer_session_token": "customerSessionToken",
  });
});

/** @internal */
export type CheckoutPublicConfirmed$Outbound = {
  created_at: string;
  modified_at: string | null;
  id: string;
  custom_field_data?:
    | { [k: string]: string | number | boolean | string | null }
    | undefined;
  payment_processor: string;
  status: "confirmed";
  client_secret: string;
  url: string;
  expires_at: string;
  success_url: string;
  embed_origin: string | null;
  amount: number;
  discount_amount: number;
  net_amount: number;
  tax_amount: number | null;
  total_amount: number;
  currency: string;
  product_id: string;
  product_price_id: string;
  discount_id: string | null;
  allow_discount_codes: boolean;
  require_billing_address: boolean;
  is_discount_applicable: boolean;
  is_free_product_price: boolean;
  is_payment_required: boolean;
  is_payment_setup_required: boolean;
  is_payment_form_required: boolean;
  customer_id: string | null;
  is_business_customer: boolean;
  customer_name: string | null;
  customer_email: string | null;
  customer_ip_address: string | null;
  customer_billing_name: string | null;
  customer_billing_address: Address$Outbound | null;
  customer_tax_id: string | null;
  payment_processor_metadata: { [k: string]: string };
  billing_address_fields: CheckoutBillingAddressFields$Outbound;
  products: Array<CheckoutProduct$Outbound>;
  product: CheckoutProduct$Outbound;
  product_price: LegacyRecurringProductPrice$Outbound | ProductPrice$Outbound;
  discount:
    | CheckoutDiscountFixedRepeatDuration$Outbound
    | CheckoutDiscountFixedOnceForeverDuration$Outbound
    | CheckoutDiscountPercentageRepeatDuration$Outbound
    | CheckoutDiscountPercentageOnceForeverDuration$Outbound
    | null;
  organization: Organization$Outbound;
  attached_custom_fields: Array<AttachedCustomField$Outbound>;
  customer_session_token: string;
};

/** @internal */
export const CheckoutPublicConfirmed$outboundSchema: z.ZodType<
  CheckoutPublicConfirmed$Outbound,
  z.ZodTypeDef,
  CheckoutPublicConfirmed
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
  id: z.string(),
  customFieldData: z.record(
    z.nullable(
      z.union([
        z.string(),
        z.number().int(),
        z.boolean(),
        z.date().transform(v => v.toISOString()),
      ]),
    ),
  ).optional(),
  paymentProcessor: PaymentProcessor$outboundSchema,
  status: z.literal("confirmed"),
  clientSecret: z.string(),
  url: z.string(),
  expiresAt: z.date().transform(v => v.toISOString()),
  successUrl: z.string(),
  embedOrigin: z.nullable(z.string()),
  amount: z.number().int(),
  discountAmount: z.number().int(),
  netAmount: z.number().int(),
  taxAmount: z.nullable(z.number().int()),
  totalAmount: z.number().int(),
  currency: z.string(),
  productId: z.string(),
  productPriceId: z.string(),
  discountId: z.nullable(z.string()),
  allowDiscountCodes: z.boolean(),
  requireBillingAddress: z.boolean(),
  isDiscountApplicable: z.boolean(),
  isFreeProductPrice: z.boolean(),
  isPaymentRequired: z.boolean(),
  isPaymentSetupRequired: z.boolean(),
  isPaymentFormRequired: z.boolean(),
  customerId: z.nullable(z.string()),
  isBusinessCustomer: z.boolean(),
  customerName: z.nullable(z.string()),
  customerEmail: z.nullable(z.string()),
  customerIpAddress: z.nullable(z.string()),
  customerBillingName: z.nullable(z.string()),
  customerBillingAddress: z.nullable(Address$outboundSchema),
  customerTaxId: z.nullable(z.string()),
  paymentProcessorMetadata: z.record(z.string()),
  billingAddressFields: CheckoutBillingAddressFields$outboundSchema,
  products: z.array(CheckoutProduct$outboundSchema),
  product: CheckoutProduct$outboundSchema,
  productPrice: z.union([
    LegacyRecurringProductPrice$outboundSchema,
    ProductPrice$outboundSchema,
  ]),
  discount: z.nullable(
    z.union([
      CheckoutDiscountFixedRepeatDuration$outboundSchema,
      CheckoutDiscountFixedOnceForeverDuration$outboundSchema,
      CheckoutDiscountPercentageRepeatDuration$outboundSchema,
      CheckoutDiscountPercentageOnceForeverDuration$outboundSchema,
    ]),
  ),
  organization: Organization$outboundSchema,
  attachedCustomFields: z.array(AttachedCustomField$outboundSchema),
  customerSessionToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    modifiedAt: "modified_at",
    customFieldData: "custom_field_data",
    paymentProcessor: "payment_processor",
    clientSecret: "client_secret",
    expiresAt: "expires_at",
    successUrl: "success_url",
    embedOrigin: "embed_origin",
    discountAmount: "discount_amount",
    netAmount: "net_amount",
    taxAmount: "tax_amount",
    totalAmount: "total_amount",
    productId: "product_id",
    productPriceId: "product_price_id",
    discountId: "discount_id",
    allowDiscountCodes: "allow_discount_codes",
    requireBillingAddress: "require_billing_address",
    isDiscountApplicable: "is_discount_applicable",
    isFreeProductPrice: "is_free_product_price",
    isPaymentRequired: "is_payment_required",
    isPaymentSetupRequired: "is_payment_setup_required",
    isPaymentFormRequired: "is_payment_form_required",
    customerId: "customer_id",
    isBusinessCustomer: "is_business_customer",
    customerName: "customer_name",
    customerEmail: "customer_email",
    customerIpAddress: "customer_ip_address",
    customerBillingName: "customer_billing_name",
    customerBillingAddress: "customer_billing_address",
    customerTaxId: "customer_tax_id",
    paymentProcessorMetadata: "payment_processor_metadata",
    billingAddressFields: "billing_address_fields",
    productPrice: "product_price",
    attachedCustomFields: "attached_custom_fields",
    customerSessionToken: "customer_session_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CheckoutPublicConfirmed$ {
  /** @deprecated use `CheckoutPublicConfirmed$inboundSchema` instead. */
  export const inboundSchema = CheckoutPublicConfirmed$inboundSchema;
  /** @deprecated use `CheckoutPublicConfirmed$outboundSchema` instead. */
  export const outboundSchema = CheckoutPublicConfirmed$outboundSchema;
  /** @deprecated use `CheckoutPublicConfirmed$Outbound` instead. */
  export type Outbound = CheckoutPublicConfirmed$Outbound;
}

export function checkoutPublicConfirmedToJSON(
  checkoutPublicConfirmed: CheckoutPublicConfirmed,
): string {
  return JSON.stringify(
    CheckoutPublicConfirmed$outboundSchema.parse(checkoutPublicConfirmed),
  );
}

export function checkoutPublicConfirmedFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutPublicConfirmed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckoutPublicConfirmed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutPublicConfirmed' from JSON`,
  );
}
