/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AddressInput,
  AddressInput$Outbound,
  AddressInput$outboundSchema,
} from "./addressinput.js";

export type CustomerPortalCustomerUpdate = {
  billingName?: string | null | undefined;
  billingAddress?: AddressInput | null | undefined;
  taxId?: string | null | undefined;
};

/** @internal */
export type CustomerPortalCustomerUpdate$Outbound = {
  billing_name?: string | null | undefined;
  billing_address?: AddressInput$Outbound | null | undefined;
  tax_id?: string | null | undefined;
};

/** @internal */
export const CustomerPortalCustomerUpdate$outboundSchema: z.ZodType<
  CustomerPortalCustomerUpdate$Outbound,
  z.ZodTypeDef,
  CustomerPortalCustomerUpdate
> = z.object({
  billingName: z.nullable(z.string()).optional(),
  billingAddress: z.nullable(AddressInput$outboundSchema).optional(),
  taxId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    billingName: "billing_name",
    billingAddress: "billing_address",
    taxId: "tax_id",
  });
});

export function customerPortalCustomerUpdateToJSON(
  customerPortalCustomerUpdate: CustomerPortalCustomerUpdate,
): string {
  return JSON.stringify(
    CustomerPortalCustomerUpdate$outboundSchema.parse(
      customerPortalCustomerUpdate,
    ),
  );
}
