/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCancellationReason,
  CustomerCancellationReason$inboundSchema,
  CustomerCancellationReason$outboundSchema,
} from "./customercancellationreason.js";
import {
  CustomerSubscriptionProduct,
  CustomerSubscriptionProduct$inboundSchema,
  CustomerSubscriptionProduct$Outbound,
  CustomerSubscriptionProduct$outboundSchema,
} from "./customersubscriptionproduct.js";
import {
  ProductPrice,
  ProductPrice$inboundSchema,
  ProductPrice$Outbound,
  ProductPrice$outboundSchema,
} from "./productprice.js";
import {
  SubscriptionRecurringInterval,
  SubscriptionRecurringInterval$inboundSchema,
  SubscriptionRecurringInterval$outboundSchema,
} from "./subscriptionrecurringinterval.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$inboundSchema,
  SubscriptionStatus$outboundSchema,
} from "./subscriptionstatus.js";

export type CustomerSubscription = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the object.
   */
  id: string;
  amount: number | null;
  currency: string | null;
  recurringInterval: SubscriptionRecurringInterval;
  status: SubscriptionStatus;
  currentPeriodStart: Date;
  currentPeriodEnd: Date | null;
  cancelAtPeriodEnd: boolean;
  canceledAt: Date | null;
  startedAt: Date | null;
  endsAt: Date | null;
  endedAt: Date | null;
  customerId: string;
  productId: string;
  priceId: string;
  discountId: string | null;
  checkoutId: string | null;
  customerCancellationReason: CustomerCancellationReason | null;
  customerCancellationComment: string | null;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  userId: string;
  product: CustomerSubscriptionProduct;
  price: ProductPrice;
};

/** @internal */
export const CustomerSubscription$inboundSchema: z.ZodType<
  CustomerSubscription,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  modified_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  id: z.string(),
  amount: z.nullable(z.number().int()),
  currency: z.nullable(z.string()),
  recurring_interval: SubscriptionRecurringInterval$inboundSchema,
  status: SubscriptionStatus$inboundSchema,
  current_period_start: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  current_period_end: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  cancel_at_period_end: z.boolean(),
  canceled_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  started_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  ends_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  ended_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  customer_id: z.string(),
  product_id: z.string(),
  price_id: z.string(),
  discount_id: z.nullable(z.string()),
  checkout_id: z.nullable(z.string()),
  customer_cancellation_reason: z.nullable(
    CustomerCancellationReason$inboundSchema,
  ),
  customer_cancellation_comment: z.nullable(z.string()),
  user_id: z.string(),
  product: CustomerSubscriptionProduct$inboundSchema,
  price: ProductPrice$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "modified_at": "modifiedAt",
    "recurring_interval": "recurringInterval",
    "current_period_start": "currentPeriodStart",
    "current_period_end": "currentPeriodEnd",
    "cancel_at_period_end": "cancelAtPeriodEnd",
    "canceled_at": "canceledAt",
    "started_at": "startedAt",
    "ends_at": "endsAt",
    "ended_at": "endedAt",
    "customer_id": "customerId",
    "product_id": "productId",
    "price_id": "priceId",
    "discount_id": "discountId",
    "checkout_id": "checkoutId",
    "customer_cancellation_reason": "customerCancellationReason",
    "customer_cancellation_comment": "customerCancellationComment",
    "user_id": "userId",
  });
});

/** @internal */
export type CustomerSubscription$Outbound = {
  created_at: string;
  modified_at: string | null;
  id: string;
  amount: number | null;
  currency: string | null;
  recurring_interval: string;
  status: string;
  current_period_start: string;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  canceled_at: string | null;
  started_at: string | null;
  ends_at: string | null;
  ended_at: string | null;
  customer_id: string;
  product_id: string;
  price_id: string;
  discount_id: string | null;
  checkout_id: string | null;
  customer_cancellation_reason: string | null;
  customer_cancellation_comment: string | null;
  user_id: string;
  product: CustomerSubscriptionProduct$Outbound;
  price: ProductPrice$Outbound;
};

/** @internal */
export const CustomerSubscription$outboundSchema: z.ZodType<
  CustomerSubscription$Outbound,
  z.ZodTypeDef,
  CustomerSubscription
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()),
  modifiedAt: z.nullable(z.date().transform(v => v.toISOString())),
  id: z.string(),
  amount: z.nullable(z.number().int()),
  currency: z.nullable(z.string()),
  recurringInterval: SubscriptionRecurringInterval$outboundSchema,
  status: SubscriptionStatus$outboundSchema,
  currentPeriodStart: z.date().transform(v => v.toISOString()),
  currentPeriodEnd: z.nullable(z.date().transform(v => v.toISOString())),
  cancelAtPeriodEnd: z.boolean(),
  canceledAt: z.nullable(z.date().transform(v => v.toISOString())),
  startedAt: z.nullable(z.date().transform(v => v.toISOString())),
  endsAt: z.nullable(z.date().transform(v => v.toISOString())),
  endedAt: z.nullable(z.date().transform(v => v.toISOString())),
  customerId: z.string(),
  productId: z.string(),
  priceId: z.string(),
  discountId: z.nullable(z.string()),
  checkoutId: z.nullable(z.string()),
  customerCancellationReason: z.nullable(
    CustomerCancellationReason$outboundSchema,
  ),
  customerCancellationComment: z.nullable(z.string()),
  userId: z.string(),
  product: CustomerSubscriptionProduct$outboundSchema,
  price: ProductPrice$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    modifiedAt: "modified_at",
    recurringInterval: "recurring_interval",
    currentPeriodStart: "current_period_start",
    currentPeriodEnd: "current_period_end",
    cancelAtPeriodEnd: "cancel_at_period_end",
    canceledAt: "canceled_at",
    startedAt: "started_at",
    endsAt: "ends_at",
    endedAt: "ended_at",
    customerId: "customer_id",
    productId: "product_id",
    priceId: "price_id",
    discountId: "discount_id",
    checkoutId: "checkout_id",
    customerCancellationReason: "customer_cancellation_reason",
    customerCancellationComment: "customer_cancellation_comment",
    userId: "user_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomerSubscription$ {
  /** @deprecated use `CustomerSubscription$inboundSchema` instead. */
  export const inboundSchema = CustomerSubscription$inboundSchema;
  /** @deprecated use `CustomerSubscription$outboundSchema` instead. */
  export const outboundSchema = CustomerSubscription$outboundSchema;
  /** @deprecated use `CustomerSubscription$Outbound` instead. */
  export type Outbound = CustomerSubscription$Outbound;
}

export function customerSubscriptionToJSON(
  customerSubscription: CustomerSubscription,
): string {
  return JSON.stringify(
    CustomerSubscription$outboundSchema.parse(customerSubscription),
  );
}

export function customerSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<CustomerSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerSubscription' from JSON`,
  );
}
