/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { MemberRole, MemberRole$outboundSchema } from "./memberrole.js";

/**
 * Schema for adding a new member to the customer's team.
 */
export type CustomerPortalMemberCreate = {
  /**
   * The email address of the new member.
   */
  email: string;
  /**
   * The name of the new member (optional).
   */
  name?: string | null | undefined;
  role?: MemberRole | undefined;
};

/** @internal */
export type CustomerPortalMemberCreate$Outbound = {
  email: string;
  name?: string | null | undefined;
  role?: string | undefined;
};

/** @internal */
export const CustomerPortalMemberCreate$outboundSchema: z.ZodMiniType<
  CustomerPortalMemberCreate$Outbound,
  CustomerPortalMemberCreate
> = z.object({
  email: z.string(),
  name: z.optional(z.nullable(z.string())),
  role: z.optional(MemberRole$outboundSchema),
});

export function customerPortalMemberCreateToJSON(
  customerPortalMemberCreate: CustomerPortalMemberCreate,
): string {
  return JSON.stringify(
    CustomerPortalMemberCreate$outboundSchema.parse(customerPortalMemberCreate),
  );
}
