/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CustomFieldNumberProperties,
  CustomFieldNumberProperties$Outbound,
  CustomFieldNumberProperties$outboundSchema,
} from "./customfieldnumberproperties.js";

export type CustomFieldUpdateNumberMetadata =
  | string
  | number
  | number
  | boolean;

/**
 * Schema to update a custom field of type number.
 */
export type CustomFieldUpdateNumber = {
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * The key must be a string with a maximum length of **40 characters**.
   * The value must be either:
   *
   * * A string with a maximum length of **500 characters**
   * * An integer
   * * A floating-point number
   * * A boolean
   *
   * You can store up to **50 key-value pairs**.
   */
  metadata?: { [k: string]: string | number | number | boolean } | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  type: "number";
  properties?: CustomFieldNumberProperties | null | undefined;
};

/** @internal */
export type CustomFieldUpdateNumberMetadata$Outbound =
  | string
  | number
  | number
  | boolean;

/** @internal */
export const CustomFieldUpdateNumberMetadata$outboundSchema: z.ZodType<
  CustomFieldUpdateNumberMetadata$Outbound,
  z.ZodTypeDef,
  CustomFieldUpdateNumberMetadata
> = z.union([z.string(), z.number().int(), z.number(), z.boolean()]);

export function customFieldUpdateNumberMetadataToJSON(
  customFieldUpdateNumberMetadata: CustomFieldUpdateNumberMetadata,
): string {
  return JSON.stringify(
    CustomFieldUpdateNumberMetadata$outboundSchema.parse(
      customFieldUpdateNumberMetadata,
    ),
  );
}

/** @internal */
export type CustomFieldUpdateNumber$Outbound = {
  metadata?: { [k: string]: string | number | number | boolean } | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  type: "number";
  properties?: CustomFieldNumberProperties$Outbound | null | undefined;
};

/** @internal */
export const CustomFieldUpdateNumber$outboundSchema: z.ZodType<
  CustomFieldUpdateNumber$Outbound,
  z.ZodTypeDef,
  CustomFieldUpdateNumber
> = z.object({
  metadata: z.record(
    z.union([z.string(), z.number().int(), z.number(), z.boolean()]),
  ).optional(),
  name: z.nullable(z.string()).optional(),
  slug: z.nullable(z.string()).optional(),
  type: z.literal("number"),
  properties: z.nullable(CustomFieldNumberProperties$outboundSchema).optional(),
});

export function customFieldUpdateNumberToJSON(
  customFieldUpdateNumber: CustomFieldUpdateNumber,
): string {
  return JSON.stringify(
    CustomFieldUpdateNumber$outboundSchema.parse(customFieldUpdateNumber),
  );
}
