/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Address,
  Address$inboundSchema,
  Address$Outbound,
  Address$outboundSchema,
} from "./address.js";
import {
  MetadataOutputType,
  MetadataOutputType$inboundSchema,
  MetadataOutputType$Outbound,
  MetadataOutputType$outboundSchema,
} from "./metadataoutputtype.js";
import {
  TaxIDFormat,
  TaxIDFormat$inboundSchema,
  TaxIDFormat$outboundSchema,
} from "./taxidformat.js";

export type CustomerTeamTaxId = string | TaxIDFormat;

/**
 * A team customer in an organization.
 */
export type CustomerTeam = {
  /**
   * The ID of the customer.
   */
  id: string;
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  metadata: { [k: string]: MetadataOutputType };
  /**
   * The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
   */
  externalId?: string | null | undefined;
  /**
   * The email address of the customer. This must be unique within the organization.
   */
  email?: string | null | undefined;
  /**
   * Whether the customer email address is verified. The address is automatically verified when the customer accesses the customer portal using their email address.
   */
  emailVerified: boolean;
  /**
   * The type of customer. Team customers can have multiple members.
   */
  type: "team";
  /**
   * The name of the customer.
   */
  name: string | null;
  billingAddress: Address | null;
  taxId: Array<string | TaxIDFormat | null> | null;
  locale?: string | null | undefined;
  /**
   * The ID of the organization owning the customer.
   */
  organizationId: string;
  /**
   * Timestamp for when the customer was soft deleted.
   */
  deletedAt: Date | null;
  avatarUrl: string;
};

/** @internal */
export const CustomerTeamTaxId$inboundSchema: z.ZodMiniType<
  CustomerTeamTaxId,
  unknown
> = smartUnion([z.string(), TaxIDFormat$inboundSchema]);
/** @internal */
export type CustomerTeamTaxId$Outbound = string | string;

/** @internal */
export const CustomerTeamTaxId$outboundSchema: z.ZodMiniType<
  CustomerTeamTaxId$Outbound,
  CustomerTeamTaxId
> = smartUnion([z.string(), TaxIDFormat$outboundSchema]);

export function customerTeamTaxIdToJSON(
  customerTeamTaxId: CustomerTeamTaxId,
): string {
  return JSON.stringify(
    CustomerTeamTaxId$outboundSchema.parse(customerTeamTaxId),
  );
}
export function customerTeamTaxIdFromJSON(
  jsonString: string,
): SafeParseResult<CustomerTeamTaxId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerTeamTaxId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerTeamTaxId' from JSON`,
  );
}

/** @internal */
export const CustomerTeam$inboundSchema: z.ZodMiniType<CustomerTeam, unknown> =
  z.pipe(
    z.object({
      id: z.string(),
      created_at: z.pipe(
        z.iso.datetime({ offset: true }),
        z.transform(v => new Date(v)),
      ),
      modified_at: z.nullable(
        z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
      ),
      metadata: z.record(z.string(), MetadataOutputType$inboundSchema),
      external_id: z.optional(z.nullable(z.string())),
      email: z.optional(z.nullable(z.string())),
      email_verified: z.boolean(),
      type: z.literal("team"),
      name: z.nullable(z.string()),
      billing_address: z.nullable(Address$inboundSchema),
      tax_id: z.nullable(
        z.array(
          z.nullable(smartUnion([z.string(), TaxIDFormat$inboundSchema])),
        ),
      ),
      locale: z.optional(z.nullable(z.string())),
      organization_id: z.string(),
      deleted_at: z.nullable(
        z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
      ),
      avatar_url: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
        "modified_at": "modifiedAt",
        "external_id": "externalId",
        "email_verified": "emailVerified",
        "billing_address": "billingAddress",
        "tax_id": "taxId",
        "organization_id": "organizationId",
        "deleted_at": "deletedAt",
        "avatar_url": "avatarUrl",
      });
    }),
  );
/** @internal */
export type CustomerTeam$Outbound = {
  id: string;
  created_at: string;
  modified_at: string | null;
  metadata: { [k: string]: MetadataOutputType$Outbound };
  external_id?: string | null | undefined;
  email?: string | null | undefined;
  email_verified: boolean;
  type: "team";
  name: string | null;
  billing_address: Address$Outbound | null;
  tax_id: Array<string | string | null> | null;
  locale?: string | null | undefined;
  organization_id: string;
  deleted_at: string | null;
  avatar_url: string;
};

/** @internal */
export const CustomerTeam$outboundSchema: z.ZodMiniType<
  CustomerTeam$Outbound,
  CustomerTeam
> = z.pipe(
  z.object({
    id: z.string(),
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    modifiedAt: z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    metadata: z.record(z.string(), MetadataOutputType$outboundSchema),
    externalId: z.optional(z.nullable(z.string())),
    email: z.optional(z.nullable(z.string())),
    emailVerified: z.boolean(),
    type: z.literal("team"),
    name: z.nullable(z.string()),
    billingAddress: z.nullable(Address$outboundSchema),
    taxId: z.nullable(
      z.array(z.nullable(smartUnion([z.string(), TaxIDFormat$outboundSchema]))),
    ),
    locale: z.optional(z.nullable(z.string())),
    organizationId: z.string(),
    deletedAt: z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    avatarUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      createdAt: "created_at",
      modifiedAt: "modified_at",
      externalId: "external_id",
      emailVerified: "email_verified",
      billingAddress: "billing_address",
      taxId: "tax_id",
      organizationId: "organization_id",
      deletedAt: "deleted_at",
      avatarUrl: "avatar_url",
    });
  }),
);

export function customerTeamToJSON(customerTeam: CustomerTeam): string {
  return JSON.stringify(CustomerTeam$outboundSchema.parse(customerTeam));
}
export function customerTeamFromJSON(
  jsonString: string,
): SafeParseResult<CustomerTeam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerTeam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerTeam' from JSON`,
  );
}
