/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Order's invoice data.
 */
export type CustomerOrderInvoice = {
  /**
   * The URL to the invoice.
   */
  url: string;
};

/** @internal */
export const CustomerOrderInvoice$inboundSchema: z.ZodMiniType<
  CustomerOrderInvoice,
  unknown
> = z.object({
  url: types.string(),
});

export function customerOrderInvoiceFromJSON(
  jsonString: string,
): SafeParseResult<CustomerOrderInvoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerOrderInvoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerOrderInvoice' from JSON`,
  );
}
