/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: af4814c75d62
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CustomFieldSortProperty = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  Slug: "slug",
  MinusSlug: "-slug",
  Name: "name",
  MinusName: "-name",
  Type: "type",
  MinusType: "-type",
} as const;
export type CustomFieldSortProperty = ClosedEnum<
  typeof CustomFieldSortProperty
>;

/** @internal */
export const CustomFieldSortProperty$outboundSchema: z.ZodMiniEnum<
  typeof CustomFieldSortProperty
> = z.enum(CustomFieldSortProperty);
