/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  S3FileUploadCompletedPart,
  S3FileUploadCompletedPart$inboundSchema,
  S3FileUploadCompletedPart$Outbound,
  S3FileUploadCompletedPart$outboundSchema,
} from "./s3fileuploadcompletedpart.js";

export type FileUploadCompleted = {
  id: string;
  path: string;
  parts: Array<S3FileUploadCompletedPart>;
};

/** @internal */
export const FileUploadCompleted$inboundSchema: z.ZodType<
  FileUploadCompleted,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  path: z.string(),
  parts: z.array(S3FileUploadCompletedPart$inboundSchema),
});

/** @internal */
export type FileUploadCompleted$Outbound = {
  id: string;
  path: string;
  parts: Array<S3FileUploadCompletedPart$Outbound>;
};

/** @internal */
export const FileUploadCompleted$outboundSchema: z.ZodType<
  FileUploadCompleted$Outbound,
  z.ZodTypeDef,
  FileUploadCompleted
> = z.object({
  id: z.string(),
  path: z.string(),
  parts: z.array(S3FileUploadCompletedPart$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileUploadCompleted$ {
  /** @deprecated use `FileUploadCompleted$inboundSchema` instead. */
  export const inboundSchema = FileUploadCompleted$inboundSchema;
  /** @deprecated use `FileUploadCompleted$outboundSchema` instead. */
  export const outboundSchema = FileUploadCompleted$outboundSchema;
  /** @deprecated use `FileUploadCompleted$Outbound` instead. */
  export type Outbound = FileUploadCompleted$Outbound;
}
