/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LicenseKeyRead,
  LicenseKeyRead$inboundSchema,
} from "./licensekeyread.js";

export type LicenseKeyActivationReadMeta = string | number | number | boolean;

export type LicenseKeyActivationRead = {
  id: string;
  licenseKeyId: string;
  label: string;
  meta: { [k: string]: string | number | number | boolean };
  createdAt: Date;
  modifiedAt: Date | null;
  licenseKey: LicenseKeyRead;
};

/** @internal */
export const LicenseKeyActivationReadMeta$inboundSchema: z.ZodMiniType<
  LicenseKeyActivationReadMeta,
  unknown
> = smartUnion([
  types.string(),
  types.number(),
  types.number(),
  types.boolean(),
]);

export function licenseKeyActivationReadMetaFromJSON(
  jsonString: string,
): SafeParseResult<LicenseKeyActivationReadMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseKeyActivationReadMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseKeyActivationReadMeta' from JSON`,
  );
}

/** @internal */
export const LicenseKeyActivationRead$inboundSchema: z.ZodMiniType<
  LicenseKeyActivationRead,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    license_key_id: types.string(),
    label: types.string(),
    meta: z.record(
      z.string(),
      smartUnion([
        types.string(),
        types.number(),
        types.number(),
        types.boolean(),
      ]),
    ),
    created_at: types.date(),
    modified_at: types.nullable(types.date()),
    license_key: LicenseKeyRead$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "license_key_id": "licenseKeyId",
      "created_at": "createdAt",
      "modified_at": "modifiedAt",
      "license_key": "licenseKey",
    });
  }),
);

export function licenseKeyActivationReadFromJSON(
  jsonString: string,
): SafeParseResult<LicenseKeyActivationRead, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LicenseKeyActivationRead$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LicenseKeyActivationRead' from JSON`,
  );
}
