/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    BenefitAds,
    BenefitAds$inboundSchema,
    BenefitAds$Outbound,
    BenefitAds$outboundSchema,
} from "./benefitads.js";
import {
    BenefitArticles,
    BenefitArticles$inboundSchema,
    BenefitArticles$Outbound,
    BenefitArticles$outboundSchema,
} from "./benefitarticles.js";
import {
    BenefitCustom,
    BenefitCustom$inboundSchema,
    BenefitCustom$Outbound,
    BenefitCustom$outboundSchema,
} from "./benefitcustom.js";
import {
    BenefitDiscordOutput,
    BenefitDiscordOutput$inboundSchema,
    BenefitDiscordOutput$Outbound,
    BenefitDiscordOutput$outboundSchema,
} from "./benefitdiscordoutput.js";
import {
    BenefitDownloadables,
    BenefitDownloadables$inboundSchema,
    BenefitDownloadables$Outbound,
    BenefitDownloadables$outboundSchema,
} from "./benefitdownloadables.js";
import {
    BenefitGitHubRepository,
    BenefitGitHubRepository$inboundSchema,
    BenefitGitHubRepository$Outbound,
    BenefitGitHubRepository$outboundSchema,
} from "./benefitgithubrepository.js";
import {
    BenefitLicenseKeysOutput,
    BenefitLicenseKeysOutput$inboundSchema,
    BenefitLicenseKeysOutput$Outbound,
    BenefitLicenseKeysOutput$outboundSchema,
} from "./benefitlicensekeysoutput.js";
import {
    Pagination,
    Pagination$inboundSchema,
    Pagination$Outbound,
    Pagination$outboundSchema,
} from "./pagination.js";
import * as z from "zod";

export type Benefit =
    | BenefitArticles
    | BenefitAds
    | BenefitDiscordOutput
    | BenefitGitHubRepository
    | BenefitDownloadables
    | BenefitLicenseKeysOutput
    | BenefitCustom;

export type ListResourceBenefit = {
    items: Array<
        | BenefitArticles
        | BenefitAds
        | BenefitDiscordOutput
        | BenefitGitHubRepository
        | BenefitDownloadables
        | BenefitLicenseKeysOutput
        | BenefitCustom
    >;
    pagination: Pagination;
};

/** @internal */
export const Benefit$inboundSchema: z.ZodType<Benefit, z.ZodTypeDef, unknown> = z.union([
    BenefitArticles$inboundSchema,
    BenefitAds$inboundSchema,
    BenefitDiscordOutput$inboundSchema,
    BenefitGitHubRepository$inboundSchema,
    BenefitDownloadables$inboundSchema,
    BenefitLicenseKeysOutput$inboundSchema,
    BenefitCustom$inboundSchema,
]);

/** @internal */
export type Benefit$Outbound =
    | BenefitArticles$Outbound
    | BenefitAds$Outbound
    | BenefitDiscordOutput$Outbound
    | BenefitGitHubRepository$Outbound
    | BenefitDownloadables$Outbound
    | BenefitLicenseKeysOutput$Outbound
    | BenefitCustom$Outbound;

/** @internal */
export const Benefit$outboundSchema: z.ZodType<Benefit$Outbound, z.ZodTypeDef, Benefit> = z.union([
    BenefitArticles$outboundSchema,
    BenefitAds$outboundSchema,
    BenefitDiscordOutput$outboundSchema,
    BenefitGitHubRepository$outboundSchema,
    BenefitDownloadables$outboundSchema,
    BenefitLicenseKeysOutput$outboundSchema,
    BenefitCustom$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Benefit$ {
    /** @deprecated use `Benefit$inboundSchema` instead. */
    export const inboundSchema = Benefit$inboundSchema;
    /** @deprecated use `Benefit$outboundSchema` instead. */
    export const outboundSchema = Benefit$outboundSchema;
    /** @deprecated use `Benefit$Outbound` instead. */
    export type Outbound = Benefit$Outbound;
}

/** @internal */
export const ListResourceBenefit$inboundSchema: z.ZodType<
    ListResourceBenefit,
    z.ZodTypeDef,
    unknown
> = z.object({
    items: z.array(
        z.union([
            BenefitArticles$inboundSchema,
            BenefitAds$inboundSchema,
            BenefitDiscordOutput$inboundSchema,
            BenefitGitHubRepository$inboundSchema,
            BenefitDownloadables$inboundSchema,
            BenefitLicenseKeysOutput$inboundSchema,
            BenefitCustom$inboundSchema,
        ])
    ),
    pagination: Pagination$inboundSchema,
});

/** @internal */
export type ListResourceBenefit$Outbound = {
    items: Array<
        | BenefitArticles$Outbound
        | BenefitAds$Outbound
        | BenefitDiscordOutput$Outbound
        | BenefitGitHubRepository$Outbound
        | BenefitDownloadables$Outbound
        | BenefitLicenseKeysOutput$Outbound
        | BenefitCustom$Outbound
    >;
    pagination: Pagination$Outbound;
};

/** @internal */
export const ListResourceBenefit$outboundSchema: z.ZodType<
    ListResourceBenefit$Outbound,
    z.ZodTypeDef,
    ListResourceBenefit
> = z.object({
    items: z.array(
        z.union([
            BenefitArticles$outboundSchema,
            BenefitAds$outboundSchema,
            BenefitDiscordOutput$outboundSchema,
            BenefitGitHubRepository$outboundSchema,
            BenefitDownloadables$outboundSchema,
            BenefitLicenseKeysOutput$outboundSchema,
            BenefitCustom$outboundSchema,
        ])
    ),
    pagination: Pagination$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListResourceBenefit$ {
    /** @deprecated use `ListResourceBenefit$inboundSchema` instead. */
    export const inboundSchema = ListResourceBenefit$inboundSchema;
    /** @deprecated use `ListResourceBenefit$outboundSchema` instead. */
    export const outboundSchema = ListResourceBenefit$outboundSchema;
    /** @deprecated use `ListResourceBenefit$Outbound` instead. */
    export type Outbound = ListResourceBenefit$Outbound;
}
