/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Pagination, Pagination$inboundSchema } from "./pagination.js";
import { PaymentMethod, PaymentMethod$inboundSchema } from "./paymentmethod.js";

export type ListResourcePaymentMethod = {
  items: Array<PaymentMethod>;
  pagination: Pagination;
};

/** @internal */
export const ListResourcePaymentMethod$inboundSchema: z.ZodMiniType<
  ListResourcePaymentMethod,
  unknown
> = z.object({
  items: z.array(PaymentMethod$inboundSchema),
  pagination: Pagination$inboundSchema,
});

export function listResourcePaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<ListResourcePaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResourcePaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResourcePaymentMethod' from JSON`,
  );
}
