/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Customer, Customer$inboundSchema } from "./customer.js";
import { Member, Member$inboundSchema } from "./member.js";

/**
 * A member session that can be used to authenticate as a member in the customer portal.
 */
export type MemberSession = {
  /**
   * Creation timestamp of the object.
   */
  createdAt: Date;
  /**
   * Last modification timestamp of the object.
   */
  modifiedAt: Date | null;
  /**
   * The ID of the object.
   */
  id: string;
  token: string;
  expiresAt: Date;
  returnUrl: string | null;
  memberPortalUrl: string;
  memberId: string;
  /**
   * A member of a customer.
   */
  member: Member;
  customerId: string;
  /**
   * A customer in an organization.
   */
  customer: Customer;
};

/** @internal */
export const MemberSession$inboundSchema: z.ZodMiniType<
  MemberSession,
  unknown
> = z.pipe(
  z.object({
    created_at: types.date(),
    modified_at: types.nullable(types.date()),
    id: types.string(),
    token: types.string(),
    expires_at: types.date(),
    return_url: types.nullable(types.string()),
    member_portal_url: types.string(),
    member_id: types.string(),
    member: Member$inboundSchema,
    customer_id: types.string(),
    customer: Customer$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "modified_at": "modifiedAt",
      "expires_at": "expiresAt",
      "return_url": "returnUrl",
      "member_portal_url": "memberPortalUrl",
      "member_id": "memberId",
      "customer_id": "customerId",
    });
  }),
);

export function memberSessionFromJSON(
  jsonString: string,
): SafeParseResult<MemberSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemberSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemberSession' from JSON`,
  );
}
