/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CountAggregation,
  CountAggregation$Outbound,
  CountAggregation$outboundSchema,
} from "./countaggregation.js";
import { Filter, Filter$Outbound, Filter$outboundSchema } from "./filter.js";
import {
  PropertyAggregation,
  PropertyAggregation$Outbound,
  PropertyAggregation$outboundSchema,
} from "./propertyaggregation.js";
import {
  UniqueAggregation,
  UniqueAggregation$Outbound,
  UniqueAggregation$outboundSchema,
} from "./uniqueaggregation.js";

export type MeterUpdateMetadata = string | number | number | boolean;

export type Aggregation =
  | (PropertyAggregation & { func: "avg" })
  | (PropertyAggregation & { func: "max" })
  | (PropertyAggregation & { func: "min" })
  | (PropertyAggregation & { func: "sum" })
  | (UniqueAggregation & { func: "unique" })
  | (CountAggregation & { func: "count" });

export type MeterUpdate = {
  /**
   * Key-value object allowing you to store additional information.
   *
   * @remarks
   *
   * The key must be a string with a maximum length of **40 characters**.
   * The value must be either:
   *
   * * A string with a maximum length of **500 characters**
   * * An integer
   * * A floating-point number
   * * A boolean
   *
   * You can store up to **50 key-value pairs**.
   */
  metadata?: { [k: string]: string | number | number | boolean } | undefined;
  /**
   * The name of the meter. Will be shown on customer's invoices and usage.
   */
  name?: string | null | undefined;
  /**
   * The filter to apply on events that'll be used to calculate the meter.
   */
  filter?: Filter | null | undefined;
  /**
   * The aggregation to apply on the filtered events to calculate the meter.
   */
  aggregation?:
    | (PropertyAggregation & { func: "avg" })
    | (PropertyAggregation & { func: "max" })
    | (PropertyAggregation & { func: "min" })
    | (PropertyAggregation & { func: "sum" })
    | (UniqueAggregation & { func: "unique" })
    | (CountAggregation & { func: "count" })
    | null
    | undefined;
  /**
   * Whether the meter is archived. Archived meters are no longer used for billing.
   */
  isArchived?: boolean | null | undefined;
};

/** @internal */
export type MeterUpdateMetadata$Outbound = string | number | number | boolean;

/** @internal */
export const MeterUpdateMetadata$outboundSchema: z.ZodType<
  MeterUpdateMetadata$Outbound,
  z.ZodTypeDef,
  MeterUpdateMetadata
> = z.union([z.string(), z.number().int(), z.number(), z.boolean()]);

export function meterUpdateMetadataToJSON(
  meterUpdateMetadata: MeterUpdateMetadata,
): string {
  return JSON.stringify(
    MeterUpdateMetadata$outboundSchema.parse(meterUpdateMetadata),
  );
}

/** @internal */
export type Aggregation$Outbound =
  | (PropertyAggregation$Outbound & { func: "avg" })
  | (PropertyAggregation$Outbound & { func: "max" })
  | (PropertyAggregation$Outbound & { func: "min" })
  | (PropertyAggregation$Outbound & { func: "sum" })
  | (UniqueAggregation$Outbound & { func: "unique" })
  | (CountAggregation$Outbound & { func: "count" });

/** @internal */
export const Aggregation$outboundSchema: z.ZodType<
  Aggregation$Outbound,
  z.ZodTypeDef,
  Aggregation
> = z.union([
  PropertyAggregation$outboundSchema.and(
    z.object({ func: z.literal("avg") }).transform((v) => ({ func: v.func })),
  ),
  PropertyAggregation$outboundSchema.and(
    z.object({ func: z.literal("max") }).transform((v) => ({ func: v.func })),
  ),
  PropertyAggregation$outboundSchema.and(
    z.object({ func: z.literal("min") }).transform((v) => ({ func: v.func })),
  ),
  PropertyAggregation$outboundSchema.and(
    z.object({ func: z.literal("sum") }).transform((v) => ({ func: v.func })),
  ),
  UniqueAggregation$outboundSchema.and(
    z.object({ func: z.literal("unique") }).transform((v) => ({
      func: v.func,
    })),
  ),
  CountAggregation$outboundSchema.and(
    z.object({ func: z.literal("count") }).transform((v) => ({ func: v.func })),
  ),
]);

export function aggregationToJSON(aggregation: Aggregation): string {
  return JSON.stringify(Aggregation$outboundSchema.parse(aggregation));
}

/** @internal */
export type MeterUpdate$Outbound = {
  metadata?: { [k: string]: string | number | number | boolean } | undefined;
  name?: string | null | undefined;
  filter?: Filter$Outbound | null | undefined;
  aggregation?:
    | (PropertyAggregation$Outbound & { func: "avg" })
    | (PropertyAggregation$Outbound & { func: "max" })
    | (PropertyAggregation$Outbound & { func: "min" })
    | (PropertyAggregation$Outbound & { func: "sum" })
    | (UniqueAggregation$Outbound & { func: "unique" })
    | (CountAggregation$Outbound & { func: "count" })
    | null
    | undefined;
  is_archived?: boolean | null | undefined;
};

/** @internal */
export const MeterUpdate$outboundSchema: z.ZodType<
  MeterUpdate$Outbound,
  z.ZodTypeDef,
  MeterUpdate
> = z.object({
  metadata: z.record(
    z.union([z.string(), z.number().int(), z.number(), z.boolean()]),
  ).optional(),
  name: z.nullable(z.string()).optional(),
  filter: z.nullable(Filter$outboundSchema).optional(),
  aggregation: z.nullable(
    z.union([
      PropertyAggregation$outboundSchema.and(
        z.object({ func: z.literal("avg") }).transform((v) => ({
          func: v.func,
        })),
      ),
      PropertyAggregation$outboundSchema.and(
        z.object({ func: z.literal("max") }).transform((v) => ({
          func: v.func,
        })),
      ),
      PropertyAggregation$outboundSchema.and(
        z.object({ func: z.literal("min") }).transform((v) => ({
          func: v.func,
        })),
      ),
      PropertyAggregation$outboundSchema.and(
        z.object({ func: z.literal("sum") }).transform((v) => ({
          func: v.func,
        })),
      ),
      UniqueAggregation$outboundSchema.and(
        z.object({ func: z.literal("unique") }).transform((v) => ({
          func: v.func,
        })),
      ),
      CountAggregation$outboundSchema.and(
        z.object({ func: z.literal("count") }).transform((v) => ({
          func: v.func,
        })),
      ),
    ]),
  ).optional(),
  isArchived: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    isArchived: "is_archived",
  });
});

export function meterUpdateToJSON(meterUpdate: MeterUpdate): string {
  return JSON.stringify(MeterUpdate$outboundSchema.parse(meterUpdate));
}
