/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  S3FileCreateMultipart,
  S3FileCreateMultipart$inboundSchema,
  S3FileCreateMultipart$Outbound,
  S3FileCreateMultipart$outboundSchema,
} from "./s3filecreatemultipart.js";

export const OrganizationAvatarFileCreateService = {
  OrganizationAvatar: "organization_avatar",
} as const;
export type OrganizationAvatarFileCreateService = ClosedEnum<
  typeof OrganizationAvatarFileCreateService
>;

/**
 * Schema to create a file to be used as an organization avatar.
 */
export type OrganizationAvatarFileCreate = {
  organizationId?: string | null | undefined;
  name: string;
  /**
   * MIME type of the file. Only images are supported for this type of file.
   */
  mimeType: string;
  /**
   * Size of the file. A maximum of 1 MB is allowed for this type of file.
   */
  size: number;
  checksumSha256Base64?: string | null | undefined;
  upload: S3FileCreateMultipart;
  service?: "organization_avatar" | undefined;
  version?: string | null | undefined;
};

/** @internal */
export const OrganizationAvatarFileCreateService$inboundSchema: z.ZodNativeEnum<
  typeof OrganizationAvatarFileCreateService
> = z.nativeEnum(OrganizationAvatarFileCreateService);

/** @internal */
export const OrganizationAvatarFileCreateService$outboundSchema:
  z.ZodNativeEnum<typeof OrganizationAvatarFileCreateService> =
    OrganizationAvatarFileCreateService$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationAvatarFileCreateService$ {
  /** @deprecated use `OrganizationAvatarFileCreateService$inboundSchema` instead. */
  export const inboundSchema =
    OrganizationAvatarFileCreateService$inboundSchema;
  /** @deprecated use `OrganizationAvatarFileCreateService$outboundSchema` instead. */
  export const outboundSchema =
    OrganizationAvatarFileCreateService$outboundSchema;
}

/** @internal */
export const OrganizationAvatarFileCreate$inboundSchema: z.ZodType<
  OrganizationAvatarFileCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.nullable(z.string()).optional(),
  name: z.string(),
  mime_type: z.string(),
  size: z.number().int(),
  checksum_sha256_base64: z.nullable(z.string()).optional(),
  upload: S3FileCreateMultipart$inboundSchema,
  service: z.literal("organization_avatar").optional(),
  version: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
    "mime_type": "mimeType",
    "checksum_sha256_base64": "checksumSha256Base64",
  });
});

/** @internal */
export type OrganizationAvatarFileCreate$Outbound = {
  organization_id?: string | null | undefined;
  name: string;
  mime_type: string;
  size: number;
  checksum_sha256_base64?: string | null | undefined;
  upload: S3FileCreateMultipart$Outbound;
  service: "organization_avatar";
  version?: string | null | undefined;
};

/** @internal */
export const OrganizationAvatarFileCreate$outboundSchema: z.ZodType<
  OrganizationAvatarFileCreate$Outbound,
  z.ZodTypeDef,
  OrganizationAvatarFileCreate
> = z.object({
  organizationId: z.nullable(z.string()).optional(),
  name: z.string(),
  mimeType: z.string(),
  size: z.number().int(),
  checksumSha256Base64: z.nullable(z.string()).optional(),
  upload: S3FileCreateMultipart$outboundSchema,
  service: z.literal("organization_avatar").default("organization_avatar"),
  version: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    organizationId: "organization_id",
    mimeType: "mime_type",
    checksumSha256Base64: "checksum_sha256_base64",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationAvatarFileCreate$ {
  /** @deprecated use `OrganizationAvatarFileCreate$inboundSchema` instead. */
  export const inboundSchema = OrganizationAvatarFileCreate$inboundSchema;
  /** @deprecated use `OrganizationAvatarFileCreate$outboundSchema` instead. */
  export const outboundSchema = OrganizationAvatarFileCreate$outboundSchema;
  /** @deprecated use `OrganizationAvatarFileCreate$Outbound` instead. */
  export type Outbound = OrganizationAvatarFileCreate$Outbound;
}
