/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * `auto_accept_below_amount` is in Polar's settlement currency (USD).
 */
export type OrganizationDisputeSettings = {
  autoAcceptBelowAmount: number | null;
};

/** @internal */
export const OrganizationDisputeSettings$inboundSchema: z.ZodMiniType<
  OrganizationDisputeSettings,
  unknown
> = z.pipe(
  z.object({
    auto_accept_below_amount: z.nullable(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "auto_accept_below_amount": "autoAcceptBelowAmount",
    });
  }),
);
/** @internal */
export type OrganizationDisputeSettings$Outbound = {
  auto_accept_below_amount: number | null;
};

/** @internal */
export const OrganizationDisputeSettings$outboundSchema: z.ZodMiniType<
  OrganizationDisputeSettings$Outbound,
  OrganizationDisputeSettings
> = z.pipe(
  z.object({
    autoAcceptBelowAmount: z.nullable(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      autoAcceptBelowAmount: "auto_accept_below_amount",
    });
  }),
);

export function organizationDisputeSettingsToJSON(
  organizationDisputeSettings: OrganizationDisputeSettings,
): string {
  return JSON.stringify(
    OrganizationDisputeSettings$outboundSchema.parse(
      organizationDisputeSettings,
    ),
  );
}
export function organizationDisputeSettingsFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDisputeSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDisputeSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDisputeSettings' from JSON`,
  );
}
