/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ProductPriceSource = {
  Catalog: "catalog",
  AdHoc: "ad_hoc",
} as const;
export type ProductPriceSource = OpenEnum<typeof ProductPriceSource>;

/** @internal */
export const ProductPriceSource$inboundSchema: z.ZodMiniType<
  ProductPriceSource,
  unknown
> = openEnums.inboundSchema(ProductPriceSource);
/** @internal */
export const ProductPriceSource$outboundSchema: z.ZodMiniType<
  string,
  ProductPriceSource
> = openEnums.outboundSchema(ProductPriceSource);
