/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Schema to create a free price.
 */
export type ProductPriceFreeCreate = {
  amountType: "free";
};

/** @internal */
export type ProductPriceFreeCreate$Outbound = {
  amount_type: "free";
};

/** @internal */
export const ProductPriceFreeCreate$outboundSchema: z.ZodType<
  ProductPriceFreeCreate$Outbound,
  z.ZodTypeDef,
  ProductPriceFreeCreate
> = z.object({
  amountType: z.literal("free"),
}).transform((v) => {
  return remap$(v, {
    amountType: "amount_type",
  });
});

export function productPriceFreeCreateToJSON(
  productPriceFreeCreate: ProductPriceFreeCreate,
): string {
  return JSON.stringify(
    ProductPriceFreeCreate$outboundSchema.parse(productPriceFreeCreate),
  );
}
