/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SubscriptionSortProperty = {
  Customer: "customer",
  MinusCustomer: "-customer",
  Status: "status",
  MinusStatus: "-status",
  StartedAt: "started_at",
  MinusStartedAt: "-started_at",
  CurrentPeriodEnd: "current_period_end",
  MinusCurrentPeriodEnd: "-current_period_end",
  Amount: "amount",
  MinusAmount: "-amount",
  Product: "product",
  MinusProduct: "-product",
  Discount: "discount",
  MinusDiscount: "-discount",
} as const;
export type SubscriptionSortProperty = ClosedEnum<
  typeof SubscriptionSortProperty
>;

/** @internal */
export const SubscriptionSortProperty$outboundSchema: z.ZodNativeEnum<
  typeof SubscriptionSortProperty
> = z.nativeEnum(SubscriptionSortProperty);
