/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscriptionPausedMetadata = {
  subscriptionId: string;
  productId?: string | undefined;
  amount?: number | undefined;
  currency?: string | undefined;
  recurringInterval?: string | undefined;
  recurringIntervalCount?: number | undefined;
  pausedAt: string;
  resumesAt?: string | undefined;
};

/** @internal */
export const SubscriptionPausedMetadata$inboundSchema: z.ZodMiniType<
  SubscriptionPausedMetadata,
  unknown
> = z.pipe(
  z.object({
    subscription_id: z.string(),
    product_id: z.optional(z.string()),
    amount: z.optional(z.int()),
    currency: z.optional(z.string()),
    recurring_interval: z.optional(z.string()),
    recurring_interval_count: z.optional(z.int()),
    paused_at: z.string(),
    resumes_at: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "subscription_id": "subscriptionId",
      "product_id": "productId",
      "recurring_interval": "recurringInterval",
      "recurring_interval_count": "recurringIntervalCount",
      "paused_at": "pausedAt",
      "resumes_at": "resumesAt",
    });
  }),
);

export function subscriptionPausedMetadataFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionPausedMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionPausedMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionPausedMetadata' from JSON`,
  );
}
