/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const UserAdvertisementSortProperty = {
  CreatedAt: "created_at",
  MinusCreatedAt: "-created_at",
  Views: "views",
  MinusViews: "-views",
  Clicks: "clicks",
  MinusClicks: "-clicks",
} as const;
export type UserAdvertisementSortProperty = ClosedEnum<
  typeof UserAdvertisementSortProperty
>;

/** @internal */
export const UserAdvertisementSortProperty$inboundSchema: z.ZodNativeEnum<
  typeof UserAdvertisementSortProperty
> = z.nativeEnum(UserAdvertisementSortProperty);

/** @internal */
export const UserAdvertisementSortProperty$outboundSchema: z.ZodNativeEnum<
  typeof UserAdvertisementSortProperty
> = UserAdvertisementSortProperty$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserAdvertisementSortProperty$ {
  /** @deprecated use `UserAdvertisementSortProperty$inboundSchema` instead. */
  export const inboundSchema = UserAdvertisementSortProperty$inboundSchema;
  /** @deprecated use `UserAdvertisementSortProperty$outboundSchema` instead. */
  export const outboundSchema = UserAdvertisementSortProperty$outboundSchema;
}
