/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    ProductPriceOutput,
    ProductPriceOutput$inboundSchema,
    ProductPriceOutput$Outbound,
    ProductPriceOutput$outboundSchema,
} from "./productpriceoutput.js";
import {
    SubscriptionStatus,
    SubscriptionStatus$inboundSchema,
    SubscriptionStatus$outboundSchema,
} from "./subscriptionstatus.js";
import {
    UserSubscriptionProduct,
    UserSubscriptionProduct$inboundSchema,
    UserSubscriptionProduct$Outbound,
    UserSubscriptionProduct$outboundSchema,
} from "./usersubscriptionproduct.js";
import * as z from "zod";

export type UserSubscription = {
    /**
     * Creation timestamp of the object.
     */
    createdAt: Date;
    /**
     * Last modification timestamp of the object.
     */
    modifiedAt: Date | null;
    id: string;
    status: SubscriptionStatus;
    currentPeriodStart: Date;
    currentPeriodEnd: Date | null;
    cancelAtPeriodEnd: boolean;
    startedAt: Date | null;
    endedAt: Date | null;
    userId: string;
    productId: string;
    priceId: string | null;
    product: UserSubscriptionProduct;
    price: ProductPriceOutput | null;
};

/** @internal */
export const UserSubscription$inboundSchema: z.ZodType<UserSubscription, z.ZodTypeDef, unknown> = z
    .object({
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        modified_at: z.nullable(
            z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
        ),
        id: z.string(),
        status: SubscriptionStatus$inboundSchema,
        current_period_start: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        current_period_end: z.nullable(
            z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
        ),
        cancel_at_period_end: z.boolean(),
        started_at: z.nullable(
            z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
        ),
        ended_at: z.nullable(
            z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
        ),
        user_id: z.string(),
        product_id: z.string(),
        price_id: z.nullable(z.string()),
        product: UserSubscriptionProduct$inboundSchema,
        price: z.nullable(ProductPriceOutput$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            modified_at: "modifiedAt",
            current_period_start: "currentPeriodStart",
            current_period_end: "currentPeriodEnd",
            cancel_at_period_end: "cancelAtPeriodEnd",
            started_at: "startedAt",
            ended_at: "endedAt",
            user_id: "userId",
            product_id: "productId",
            price_id: "priceId",
        });
    });

/** @internal */
export type UserSubscription$Outbound = {
    created_at: string;
    modified_at: string | null;
    id: string;
    status: string;
    current_period_start: string;
    current_period_end: string | null;
    cancel_at_period_end: boolean;
    started_at: string | null;
    ended_at: string | null;
    user_id: string;
    product_id: string;
    price_id: string | null;
    product: UserSubscriptionProduct$Outbound;
    price: ProductPriceOutput$Outbound | null;
};

/** @internal */
export const UserSubscription$outboundSchema: z.ZodType<
    UserSubscription$Outbound,
    z.ZodTypeDef,
    UserSubscription
> = z
    .object({
        createdAt: z.date().transform((v) => v.toISOString()),
        modifiedAt: z.nullable(z.date().transform((v) => v.toISOString())),
        id: z.string(),
        status: SubscriptionStatus$outboundSchema,
        currentPeriodStart: z.date().transform((v) => v.toISOString()),
        currentPeriodEnd: z.nullable(z.date().transform((v) => v.toISOString())),
        cancelAtPeriodEnd: z.boolean(),
        startedAt: z.nullable(z.date().transform((v) => v.toISOString())),
        endedAt: z.nullable(z.date().transform((v) => v.toISOString())),
        userId: z.string(),
        productId: z.string(),
        priceId: z.nullable(z.string()),
        product: UserSubscriptionProduct$outboundSchema,
        price: z.nullable(ProductPriceOutput$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            modifiedAt: "modified_at",
            currentPeriodStart: "current_period_start",
            currentPeriodEnd: "current_period_end",
            cancelAtPeriodEnd: "cancel_at_period_end",
            startedAt: "started_at",
            endedAt: "ended_at",
            userId: "user_id",
            productId: "product_id",
            priceId: "price_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserSubscription$ {
    /** @deprecated use `UserSubscription$inboundSchema` instead. */
    export const inboundSchema = UserSubscription$inboundSchema;
    /** @deprecated use `UserSubscription$outboundSchema` instead. */
    export const outboundSchema = UserSubscription$outboundSchema;
    /** @deprecated use `UserSubscription$Outbound` instead. */
    export type Outbound = UserSubscription$Outbound;
}
