/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  WebhookEventType,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";
import {
  WebhookFormat,
  WebhookFormat$outboundSchema,
} from "./webhookformat.js";

/**
 * Schema to update a webhook endpoint.
 */
export type WebhookEndpointUpdate = {
  url?: string | null | undefined;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  secret?: string | null | undefined;
  format?: WebhookFormat | null | undefined;
  events?: Array<WebhookEventType> | null | undefined;
  /**
   * Whether the webhook endpoint is enabled.
   */
  enabled?: boolean | null | undefined;
};

/** @internal */
export type WebhookEndpointUpdate$Outbound = {
  url?: string | null | undefined;
  secret?: string | null | undefined;
  format?: string | null | undefined;
  events?: Array<string> | null | undefined;
  enabled?: boolean | null | undefined;
};

/** @internal */
export const WebhookEndpointUpdate$outboundSchema: z.ZodType<
  WebhookEndpointUpdate$Outbound,
  z.ZodTypeDef,
  WebhookEndpointUpdate
> = z.object({
  url: z.nullable(z.string()).optional(),
  secret: z.nullable(z.string()).optional(),
  format: z.nullable(WebhookFormat$outboundSchema).optional(),
  events: z.nullable(z.array(WebhookEventType$outboundSchema)).optional(),
  enabled: z.nullable(z.boolean()).optional(),
});

export function webhookEndpointUpdateToJSON(
  webhookEndpointUpdate: WebhookEndpointUpdate,
): string {
  return JSON.stringify(
    WebhookEndpointUpdate$outboundSchema.parse(webhookEndpointUpdate),
  );
}
