/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Subscription,
  Subscription$inboundSchema,
  Subscription$Outbound,
  Subscription$outboundSchema,
} from "./subscription.js";

/**
 * Sent when a paused subscription resumes, restoring the customer's access.
 *
 * @remarks
 *
 * Resuming starts a new billing period and charges the customer immediately.
 *
 * **Discord & Slack support:** Full
 */
export type WebhookSubscriptionResumedPayload = {
  type: "subscription.resumed";
  timestamp: Date;
  data: Subscription;
};

/** @internal */
export const WebhookSubscriptionResumedPayload$inboundSchema: z.ZodMiniType<
  WebhookSubscriptionResumedPayload,
  unknown
> = z.object({
  type: z.literal("subscription.resumed"),
  timestamp: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
  data: Subscription$inboundSchema,
});
/** @internal */
export type WebhookSubscriptionResumedPayload$Outbound = {
  type: "subscription.resumed";
  timestamp: string;
  data: Subscription$Outbound;
};

/** @internal */
export const WebhookSubscriptionResumedPayload$outboundSchema: z.ZodMiniType<
  WebhookSubscriptionResumedPayload$Outbound,
  WebhookSubscriptionResumedPayload
> = z.object({
  type: z.literal("subscription.resumed"),
  timestamp: z.pipe(z.date(), z.transform(v => v.toISOString())),
  data: Subscription$outboundSchema,
});

export function webhookSubscriptionResumedPayloadToJSON(
  webhookSubscriptionResumedPayload: WebhookSubscriptionResumedPayload,
): string {
  return JSON.stringify(
    WebhookSubscriptionResumedPayload$outboundSchema.parse(
      webhookSubscriptionResumedPayload,
    ),
  );
}
export function webhookSubscriptionResumedPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionResumedPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookSubscriptionResumedPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionResumedPayload' from JSON`,
  );
}
