/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BenefitGrantWebhook,
  BenefitGrantWebhook$inboundSchema,
  BenefitGrantWebhook$Outbound,
  BenefitGrantWebhook$outboundSchema,
} from "./benefitgrantwebhook.js";

/**
 * Sent when a benefit grant is revoked.
 *
 * @remarks
 *
 * **Discord & Slack support:** Basic
 */
export type WebhookBenefitGrantRevokedPayload = {
  type: "benefit_grant.revoked";
  data: BenefitGrantWebhook;
};

/** @internal */
export const WebhookBenefitGrantRevokedPayload$inboundSchema: z.ZodType<
  WebhookBenefitGrantRevokedPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("benefit_grant.revoked"),
  data: BenefitGrantWebhook$inboundSchema,
});

/** @internal */
export type WebhookBenefitGrantRevokedPayload$Outbound = {
  type: "benefit_grant.revoked";
  data: BenefitGrantWebhook$Outbound;
};

/** @internal */
export const WebhookBenefitGrantRevokedPayload$outboundSchema: z.ZodType<
  WebhookBenefitGrantRevokedPayload$Outbound,
  z.ZodTypeDef,
  WebhookBenefitGrantRevokedPayload
> = z.object({
  type: z.literal("benefit_grant.revoked"),
  data: BenefitGrantWebhook$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WebhookBenefitGrantRevokedPayload$ {
  /** @deprecated use `WebhookBenefitGrantRevokedPayload$inboundSchema` instead. */
  export const inboundSchema = WebhookBenefitGrantRevokedPayload$inboundSchema;
  /** @deprecated use `WebhookBenefitGrantRevokedPayload$outboundSchema` instead. */
  export const outboundSchema =
    WebhookBenefitGrantRevokedPayload$outboundSchema;
  /** @deprecated use `WebhookBenefitGrantRevokedPayload$Outbound` instead. */
  export type Outbound = WebhookBenefitGrantRevokedPayload$Outbound;
}

export function webhookBenefitGrantRevokedPayloadToJSON(
  webhookBenefitGrantRevokedPayload: WebhookBenefitGrantRevokedPayload,
): string {
  return JSON.stringify(
    WebhookBenefitGrantRevokedPayload$outboundSchema.parse(
      webhookBenefitGrantRevokedPayload,
    ),
  );
}

export function webhookBenefitGrantRevokedPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookBenefitGrantRevokedPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookBenefitGrantRevokedPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookBenefitGrantRevokedPayload' from JSON`,
  );
}
